# Downstream Analysis

This notebook should be used for downstream analysis of your OPS screen.
Cells marked with <font color='red'>SET PARAMETERS</font> contain crucial variables that need to be set according to your specific experimental setup and data organization.
Please review and modify these variables as needed before proceeding with the analysis.

## <font color='red'>SET PARAMETERS</font>

### Fixed parameters for cluster module

- `CONFIG_FILE_PATH`: Path to a Brieflow config file used during processing. Absolute or relative to where workflows are run from.

In [18]:
CONFIG_FILE_PATH = "config/config.yml"

In [19]:
from pathlib import Path
import warnings
warnings.filterwarnings('ignore', category=UserWarning)
import yaml
import pandas as pd
import matplotlib as plt

from lib.cluster.cluster_analysis import (
    differential_analysis, 
    waterfall_plot, 
    two_feature_plot, 
    cluster_heatmap
)
from lib.cluster.phate_leiden_clustering import plot_phate_leiden_clusters
from lib.shared.metrics import get_all_stats

In [20]:
# load config file and determine root path
with open(CONFIG_FILE_PATH, "r") as config_file:
    config = yaml.safe_load(config_file)
    ROOT_FP = Path(config["all"]["root_fp"])

## Pipeline Statistics Report

This function analyzes the entire data processing pipeline from raw microscopy images to clustered perturbation profiles. It will:

1. **Preprocessing**: Count input files and generated image tiles
2. **SBS**: Analyze cell segmentation and barcode mapping success rates
3. **Phenotype**: Count cells and morphological features extracted
4. **Merge**: Calculate how many cells were successfully matched between SBS and phenotype data
5. **Aggregation**: Measure perturbation coverage and batch effect correction (per cell class/channel)
6. **Clustering**: Evaluate pathway enrichment and optimal clustering parameters

**Expected runtime: 5-15 minutes** depending on dataset size, as this function loads and analyzes large parquet files to calculate batch statistics and enrichment metrics.

The report will display progress updates as each stage is analyzed.

In [4]:
statistics = get_all_stats(config)

================================================================================
PIPELINE STATISTICS REPORT
================================================================================

[1/6] Gathering preprocessing statistics...

 PREPROCESSING STATISTICS:
   • ND2 input files: 38,670
   • SBS tiles generated: 22,620
   • Phenotype tiles generated: 8,025

[2/6] Gathering SBS statistics...

 SBS STATISTICS:
   • Total cells segmented: 5,193,329
   • Cells with barcode: 59.4% (3,086,044 cells)
   • Cells with unique gene mapping: 47.1% (2,444,937 cells)

[3/6] Gathering phenotype statistics...

 PHENOTYPE STATISTICS:
   • Total cells segmented: 5,369,034
   • Number of morphological features: 3,571

[4/6] Gathering merge statistics...

 MERGE STATISTICS:
   • Total cells processed: 2,674,264
   • Successfully mapped cells: 2,444,976
   • Average mapping rate: 91.4%

[5/6] Gathering aggregation statistics...
   (This may take a moment as it processes multiple cell class/channel combinations...)
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI_ACA_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI_ACA_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-ACA_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-ACA_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI_MITOTRACKER_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Interphase_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Interphase_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Interphase_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Interphase_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Interphase_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Interphase_ChCo-DAPI_VIMENTIN_ITGB1__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI_ACA_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI_ACA_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-ACA_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-ACA_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI_MITOTRACKER_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-Mitotic_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-Mitotic_ChCo-DAPI_VIMENTIN_ITGB1__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI_ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI_ACA_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI_ACA_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-ACA_CENPT__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-ACA_CENPT__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-ACA_CENPT__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI_MITOTRACKER_WGA__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI_MITOTRACKER_WGA__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI_VIMENTIN_PHALLOIDIN_ITGB1__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A3_CeCl-all_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B3_CeCl-all_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B1_CeCl-all_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-A2_CeCl-all_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet
Reading first 1,000 rows from brieflow_output/aggregate/parquets/P-1_W-B2_CeCl-all_ChCo-DAPI_VIMENTIN_ITGB1__filtered.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:355: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_control_data["batch"] = (
/lab/barcheese01/mdiberna/miniconda3/envs/brieflow_kilimanjaro/lib/python3.11/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

Reading first 1,000 rows from brieflow_output/aggregate/parquets/CeCl-all_ChCo-DAPI_VIMENTIN_ITGB1__aligned.parquet

/lab/ops_analysis/cheeseman/kilimanjaro-analysis/brieflow/workflow/lib/shared/metrics.py:391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_control_data["batch"] = (

 AGGREGATION STATISTICS:

   Interphase cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 1371
      • Batch effect reduction: 0.3709 → 0.5242

   Interphase cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 1232
      • Batch effect reduction: 0.4230 → 0.4816

   Interphase cells - DAPI_ACA_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 584
      • Batch effect reduction: 0.4583 → 0.4536

   Interphase cells - DAPI_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 429
      • Batch effect reduction: 0.4722 → 0.5237

   Interphase cells - ACA_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 418
      • Batch effect reduction: 0.4501 → 0.4738

   Interphase cells - DAPI:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 259
      • Batch effect reduction: 0.4489 → 0.6453

   Interphase cells - DAPI_MITOTRACKER_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 259
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 585
      • Batch effect reduction: 0.4098 → 0.5034

   Interphase cells - DAPI_VIMENTIN_PHALLOIDIN_ITGB1:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 727
      • Batch effect reduction: 0.3755 → 0.4956

   Interphase cells - DAPI_VIMENTIN_ITGB1:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 258
      • Total cells (pre-filter): 2,945,339
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 1,412,773
      • PC features: 581
      • Batch effect reduction: 0.4831 → 0.4980

   Mitotic cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 143
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 1400
      • Batch effect reduction: 0.2637 → 0.4605

   Mitotic cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 143
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 1264
      • Batch effect reduction: 0.2741 → 0.4910

   Mitotic cells - DAPI_ACA_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 143
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 590
      • Batch effect reduction: 0.3536 → 0.5460

   Mitotic cells - DAPI_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 143
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 432
      • Batch effect reduction: 0.4034 → 0.5468

   Mitotic cells - ACA_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 144
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 425
      • Batch effect reduction: 0.3875 → 0.4861

   Mitotic cells - DAPI:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 144
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 262
      • Batch effect reduction: 0.3919 → 0.5342

   Mitotic cells - DAPI_MITOTRACKER_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 143
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 599
      • Batch effect reduction: 0.3197 → 0.4013

   Mitotic cells - DAPI_VIMENTIN_PHALLOIDIN_ITGB1:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 144
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 743
      • Batch effect reduction: 0.2707 → 0.4875

   Mitotic cells - DAPI_VIMENTIN_ITGB1:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 144
      • Total cells (pre-filter): 1,673,268
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 784,611
      • PC features: 595
      • Batch effect reduction: 0.2861 → 0.4799

   all cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 403
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 1382
      • Batch effect reduction: 0.3145 → 0.5232

   all cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 403
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 1249
      • Batch effect reduction: 0.3477 → 0.4604

   all cells - DAPI_ACA_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 402
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 586
      • Batch effect reduction: 0.3765 → 0.5414

   all cells - DAPI_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 403
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 429
      • Batch effect reduction: 0.4367 → 0.6021

   all cells - ACA_CENPT:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 402
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 421
      • Batch effect reduction: 0.3530 → 0.5068

   all cells - DAPI:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 403
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 260
      • Batch effect reduction: 0.3677 → 0.4430

   all cells - DAPI_MITOTRACKER_WGA:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 403
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 593
      • Batch effect reduction: 0.3687 → 0.5322

   all cells - DAPI_VIMENTIN_PHALLOIDIN_ITGB1:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 403
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 734
      • Batch effect reduction: 0.3422 → 0.5733

   all cells - DAPI_VIMENTIN_ITGB1:
      • Distinct perturbations: 5,298
      • Median cells per perturbation: 403
      • Total cells (pre-filter): 4,618,607
      • Total cells (post-filter): 5,000
      • Total cells (aggregated): 2,197,385
      • PC features: 590
      • Batch effect reduction: 0.3824 → 0.4832

[6/6] Gathering clustering statistics...
   (Analyzing enrichment results across multiple resolutions...)

🌐 CLUSTERING STATISTICS:

   Best resolution for each cell class/channel combination:

   Interphase cells - ACA_CENPT:
      • Best resolution: 5
      • Number of clusters: 220
      • Enriched clusters (real): 5.6%
      • Enriched clusters (shuffled): 0.7%
      • Fold enrichment: 8.41x
      • Statistical significance: *** (p_adj = 3.458e-05)

   Interphase cells - DAPI:
      • Best resolution: 6
      • Number of clusters: 273
      • Enriched clusters (real): 3.9%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 385487528.34x
      • Statistical significance: *** (p_adj = 9.219e-07)

   Interphase cells - DAPI_ACA_CENPT:
      • Best resolution: 6
      • Number of clusters: 251
      • Enriched clusters (real): 5.8%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 583871410.91x
      • Statistical significance: *** (p_adj = 3.375e-09)

   Interphase cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA:
      • Best resolution: 5
      • Number of clusters: 206
      • Enriched clusters (real): 10.1%
      • Enriched clusters (shuffled): 0.4%
      • Fold enrichment: 24.74x
      • Statistical significance: *** (p_adj = 2.046e-11)

   Interphase cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA:
      • Best resolution: 5
      • Number of clusters: 205
      • Enriched clusters (real): 10.9%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 1094724900.74x
      • Statistical significance: *** (p_adj = 1.383e-13)

   Interphase cells - DAPI_CENPT:
      • Best resolution: 5
      • Number of clusters: 220
      • Enriched clusters (real): 5.9%
      • Enriched clusters (shuffled): 0.4%
      • Fold enrichment: 14.86x
      • Statistical significance: *** (p_adj = 3.117e-07)

   Interphase cells - DAPI_MITOTRACKER_WGA:
      • Best resolution: 5
      • Number of clusters: 220
      • Enriched clusters (real): 8.9%
      • Enriched clusters (shuffled): 0.7%
      • Fold enrichment: 13.33x
      • Statistical significance: *** (p_adj = 4.737e-09)

   Interphase cells - DAPI_VIMENTIN_ITGB1:
      • Best resolution: 5
      • Number of clusters: 225
      • Enriched clusters (real): 6.8%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 681992337.16x
      • Statistical significance: *** (p_adj = 3.121e-09)

   Interphase cells - DAPI_VIMENTIN_PHALLOIDIN_ITGB1:
      • Best resolution: 5
      • Number of clusters: 223
      • Enriched clusters (real): 8.0%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 800768737.99x
      • Statistical significance: *** (p_adj = 4.727e-11)

   Mitotic cells - ACA_CENPT:
      • Best resolution: 5
      • Number of clusters: 249
      • Enriched clusters (real): 3.9%
      • Enriched clusters (shuffled): 0.4%
      • Fold enrichment: 9.97x
      • Statistical significance: *** (p_adj = 3.437e-05)

   Mitotic cells - DAPI:
      • Best resolution: 5
      • Number of clusters: 242
      • Enriched clusters (real): 2.5%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 254820936.64x
      • Statistical significance: *** (p_adj = 4.553e-04)

   Mitotic cells - DAPI_ACA_CENPT:
      • Best resolution: 5
      • Number of clusters: 231
      • Enriched clusters (real): 3.9%
      • Enriched clusters (shuffled): 0.4%
      • Fold enrichment: 9.94x
      • Statistical significance: *** (p_adj = 6.452e-05)

   Mitotic cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA:
      • Best resolution: 5
      • Number of clusters: 230
      • Enriched clusters (real): 5.4%
      • Enriched clusters (shuffled): 0.4%
      • Fold enrichment: 13.50x
      • Statistical significance: *** (p_adj = 6.349e-07)

   Mitotic cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA:
      • Best resolution: 6
      • Number of clusters: 266
      • Enriched clusters (real): 5.7%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 566416040.10x
      • Statistical significance: *** (p_adj = 1.832e-09)

   Mitotic cells - DAPI_CENPT:
      • Best resolution: 5
      • Number of clusters: 236
      • Enriched clusters (real): 3.9%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 386064030.13x
      • Statistical significance: *** (p_adj = 7.005e-06)

   Mitotic cells - DAPI_MITOTRACKER_WGA:
      • Best resolution: 5
      • Number of clusters: 235
      • Enriched clusters (real): 4.3%
      • Enriched clusters (shuffled): 0.4%
      • Fold enrichment: 10.77x
      • Statistical significance: *** (p_adj = 9.802e-05)

   Mitotic cells - DAPI_VIMENTIN_ITGB1:
      • Best resolution: 6
      • Number of clusters: 267
      • Enriched clusters (real): 3.0%
      • Enriched clusters (shuffled): 0.3%
      • Fold enrichment: 8.73x
      • Statistical significance: *** (p_adj = 1.155e-03)

   Mitotic cells - DAPI_VIMENTIN_PHALLOIDIN_ITGB1:
      • Best resolution: 5
      • Number of clusters: 236
      • Enriched clusters (real): 3.9%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 386064030.13x
      • Statistical significance: *** (p_adj = 7.005e-06)

   all cells - ACA_CENPT:
      • Best resolution: 7
      • Number of clusters: 289
      • Enriched clusters (real): 7.0%
      • Enriched clusters (shuffled): 0.3%
      • Fold enrichment: 22.43x
      • Statistical significance: *** (p_adj = 6.653e-11)

   all cells - DAPI:
      • Best resolution: 8
      • Number of clusters: 328
      • Enriched clusters (real): 4.6%
      • Enriched clusters (shuffled): 0.6%
      • Fold enrichment: 8.17x
      • Statistical significance: *** (p_adj = 7.501e-07)

   all cells - DAPI_ACA_CENPT:
      • Best resolution: 5
      • Number of clusters: 211
      • Enriched clusters (real): 8.6%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 862559241.71x
      • Statistical significance: *** (p_adj = 4.371e-11)

   all cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA:
      • Best resolution: 5
      • Number of clusters: 203
      • Enriched clusters (real): 13.6%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 1357635467.98x
      • Statistical significance: *** (p_adj = 7.329e-16)

   all cells - DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA:
      • Best resolution: 5
      • Number of clusters: 206
      • Enriched clusters (real): 12.8%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 1283495145.63x
      • Statistical significance: *** (p_adj = 7.411e-16)

   all cells - DAPI_CENPT:
      • Best resolution: 5
      • Number of clusters: 215
      • Enriched clusters (real): 6.9%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 694466720.13x
      • Statistical significance: *** (p_adj = 3.024e-09)

   all cells - DAPI_MITOTRACKER_WGA:
      • Best resolution: 5
      • Number of clusters: 211
      • Enriched clusters (real): 8.8%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 876777251.18x
      • Statistical significance: *** (p_adj = 2.223e-11)

   all cells - DAPI_VIMENTIN_ITGB1:
      • Best resolution: 5
      • Number of clusters: 220
      • Enriched clusters (real): 7.4%
      • Enriched clusters (shuffled): 0.0%
      • Fold enrichment: 740469208.21x
      • Statistical significance: *** (p_adj = 7.276e-10)

   all cells - DAPI_VIMENTIN_PHALLOIDIN_ITGB1:
      • Best resolution: 5
      • Number of clusters: 211
      • Enriched clusters (real): 9.4%
      • Enriched clusters (shuffled): 0.8%
      • Fold enrichment: 11.52x
      • Statistical significance: *** (p_adj = 7.014e-10)

================================================================================
REPORT COMPLETE
================================================================================

In [21]:
# Load cell classes and channel combos
cluster_combo_fp = config["cluster"]["cluster_combo_fp"]
cluster_combos = pd.read_csv(cluster_combo_fp, sep="\t")

CHANNEL_COMBOS = list(cluster_combos["channel_combo"].unique())
print(f"Channel Combos: {CHANNEL_COMBOS}")

CELL_CLASSES = list(cluster_combos["cell_class"].unique())
print(f"Cell classes: {CELL_CLASSES}")

LEIDEN_RESOLUTION = list(cluster_combos["leiden_resolution"].unique())
print(f"Leiden resolution: {LEIDEN_RESOLUTION}")

Channel Combos: ['DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_PHALLOIDIN_WGA', 'DAPI_ACA_MITOTRACKER_VIMENTIN_CENPT_ITGB1_WGA', 'DAPI_ACA_CENPT', 'DAPI_CENPT', 'ACA_CENPT', 'DAPI', 'DAPI_MITOTRACKER_WGA', 'DAPI_VIMENTIN_PHALLOIDIN_ITGB1', 'DAPI_VIMENTIN_ITGB1']
Cell classes: ['Interphase', 'Mitotic', 'all']
Leiden resolution: [np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17)]

## <font color='red'>SET PARAMETERS</font>

### Cluster Selection for Analysis

Set these parameters to select the specific cluster data to analyze:
- `CHANNEL_COMBO`: Select from available channel combinations,
- `CELL_CLASS`: Select from available cell classes,
- `LEIDEN_RESOLUTION`: Select from available Leiden resolutions,

These parameters determine which folder of cluster data will be analyzed.

In [22]:
CHANNEL_COMBO = "DAPI_VIMENTIN_ITGB1"
CELL_CLASS = "Interphase"
LEIDEN_RESOLUTION = 15

In [23]:
aggregate_file = ROOT_FP / "aggregate" / "tsvs" / f"CeCl-{CELL_CLASS}_ChCo-{CHANNEL_COMBO}__feature_table.tsv"
print(f"Aggregate file: {aggregate_file}")

if not aggregate_file.exists():
    print(f"Aggregate file does not exist: {aggregate_file}")
else:
    print(f"Aggregate file found")

cluster_path = ROOT_FP / "cluster" / CHANNEL_COMBO / CELL_CLASS / str(LEIDEN_RESOLUTION)
print(f"Cluster path: {cluster_path}")

if not cluster_path.exists():
    print(f"Cluster directory does not exist: {cluster_path}")
else:
    print(f"Cluster directory found")

Aggregate file: brieflow_output/aggregate/tsvs/CeCl-Interphase_ChCo-DAPI_VIMENTIN_ITGB1__feature_table.tsv
Aggregate file found
Cluster path: brieflow_output/cluster/DAPI_VIMENTIN_ITGB1/Interphase/15
Cluster directory found

## Feature Plot Analysis

This section generates visualizations to explore the phenotypic effects of gene perturbations in your screen. The plots will help you:

1. **Differential Feature Analysis**: Identify genes with significant phenotypic changes vs. controls
2. **Waterfall Plots**: Rank genes by their effect on specific features of interest
3. **Two-Feature Plots**: Discover relationships between different phenotypic measurements
4. **Heatmaps**: Visualize patterns across multiple features and gene sets simultaneously

The interactive analysis allow you to customize each visualization for your specific biological questions.

In [24]:
cluster_file = cluster_path / "phate_leiden_clustering.tsv"
cluster_df = pd.read_csv(cluster_file, sep="\t")
display(cluster_df)

,gene_symbol_0,cell_count,PHATE_0,PHATE_1,cluster,uniprot_entry,uniprot_function,uniprot_link,mean_potential_to_nontargeting,normalized_potential_to_nontargeting
0,RPL7,155,-0.117834,-0.016559,0,P18124,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/P18124/entry,7.411278,0.984631
1,RPL10,188,-0.113073,-0.015562,0,P27635,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/P27635/entry,7.111462,0.943287
2,RPL13A,208,-0.114349,-0.016143,0,P40429,Associated with ribosomes but is not required ...,https://www.uniprot.org/uniprotkb/P40429/entry,7.191240,0.954288
3,PEX13,290,-0.067548,-0.007744,0,Q92968,"Component of the PEX13-PEX14 docking complex, ...",https://www.uniprot.org/uniprotkb/Q92968/entry,4.263796,0.550602
4,BOP1,190,-0.088212,-0.010658,0,Q14137,"Component of the PeBoW complex, which is requi...",https://www.uniprot.org/uniprotkb/Q14137/entry,5.553396,0.728434
...,...,...,...,...,...,...,...,...,...,...
5291,MTCH2,263,0.000792,0.001325,508,Q9Y6C9,Protein insertase that mediates insertion of t...,https://www.uniprot.org/uniprotkb/Q9Y6C9/entry,0.337854,0.009226
5292,XRCC6,299,-0.000930,-0.011476,508,P12956,Single-stranded DNA-dependent ATP-dependent he...,https://www.uniprot.org/uniprotkb/P12956/entry,0.975402,0.097142
5293,COA3,128,0.002222,-0.000950,508,Q9Y2R0,Core component of the MITRAC (mitochondrial tr...,https://www.uniprot.org/uniprotkb/Q9Y2R0/entry,0.424310,0.021148
5294,CDC42,246,0.003742,-0.028796,508,P60953,Plasma membrane-associated small GTPase which ...,https://www.uniprot.org/uniprotkb/P60953/entry,1.981820,0.235924
5295,SON,158,0.003198,-0.029336,508,P18583,RNA-binding protein that acts as a mRNA splici...,https://www.uniprot.org/uniprotkb/P18583/entry,2.029083,0.242441

In [25]:
aggregate_df = pd.read_csv(aggregate_file, sep="\t")
display(aggregate_df)

,gene_symbol_0,nucleus_DAPI_int,nucleus_VIMENTIN_int,nucleus_ITGB1_int,nucleus_DAPI_mean,nucleus_VIMENTIN_mean,nucleus_ITGB1_mean,nucleus_DAPI_std,nucleus_VIMENTIN_std,nucleus_ITGB1_std,...,cytoplasm_zernike_9_1,cytoplasm_zernike_9_3,cytoplasm_zernike_9_5,cytoplasm_zernike_9_7,cytoplasm_zernike_9_9,cytoplasm_number_neighbors_1,cytoplasm_percent_touching_1,cytoplasm_first_neighbor_distance,cytoplasm_second_neighbor_distance,cytoplasm_angle_between_neighbors
0,GNPNAT1,-0.387013,-0.092880,-0.182733,-0.229288,-0.125566,-0.126174,-0.126545,-0.233545,-0.246122,...,-0.116470,-0.205580,-0.212723,-0.146224,-0.047532,0.201468,0.160078,-0.174543,-0.205126,0.111508
1,PUM3,-0.374053,-0.102638,-0.080077,-0.081511,-0.107501,-0.057703,0.025904,-0.227137,-0.144614,...,-0.069592,-0.359922,-0.141371,-0.221034,-0.196442,0.192648,0.040670,-0.112780,-0.094830,0.001732
2,RHEB,-0.375061,-0.161406,-0.024476,-0.262697,-0.230082,-0.201940,-0.134211,-0.365579,-0.157532,...,-0.230845,-0.293602,-0.196208,-0.212619,-0.200463,0.201468,0.154440,0.030258,-0.175700,0.137705
3,nontargeting_ACGCGAGTCCG_AACGCGAGTCCGGTGGCTAG,-0.372467,0.133251,0.179101,-0.310868,-0.199131,-0.054111,-0.335177,-0.270648,-0.341199,...,-0.225987,-0.186398,-0.035250,0.103974,-0.211945,0.197058,0.148834,-0.099650,-0.119731,0.388502
4,TAF13,-0.401358,0.006040,-0.140678,-0.164871,0.039769,-0.052171,-0.062150,-0.064739,-0.235439,...,-0.166911,-0.204890,-0.117305,-0.230326,-0.166408,0.192648,0.005149,-0.054654,-0.172908,0.163137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5293,nontargeting_GCGTCAAAATT_GGCGTCAAAATTAGAAGCCG,-0.276764,-0.037022,-0.077624,-0.364590,-0.322765,-0.246466,-0.434144,-0.419682,-0.144890,...,0.096414,-0.201242,-0.227048,0.506841,0.017355,0.201468,0.200680,-0.351230,-0.377784,0.316179
5294,nontargeting_TCTCGTGCAAC_GTCTCGTGCAACCTGCGCGT,-0.353165,-0.373217,-0.397782,-0.319676,-0.434669,-0.285938,0.033455,-0.407361,-0.074336,...,-0.270972,-0.375636,0.008205,-0.391619,-0.198179,0.192648,-0.077081,-0.027281,-0.282278,-0.179875
5295,nontargeting_GCTCGCCATGT_AGCTCGCCATGTCGGTTCTC,-0.427573,-0.182177,0.026410,-0.545371,-0.186352,-0.045234,-0.115763,-0.197146,-0.228275,...,0.176935,-0.366623,-0.258207,-0.054098,-0.131305,0.201468,0.116878,-0.209514,0.023289,0.305095
5296,nontargeting_AGTCTGACGTC_GAGTCTGACGTCGACTATCT,-0.427394,-0.424283,-0.683564,-0.098043,-0.158218,-0.785250,-0.292111,-0.373255,-0.475120,...,-0.411842,-0.554681,-0.173705,-0.133141,-0.299828,0.201468,0.321007,-0.345022,-0.427735,-0.383288
5297,nontargeting_CGGTACATGCG_ACGGTACATGCGCATGAGTC,-0.470942,-0.568292,-1.070241,0.497197,0.672245,-0.113594,0.170842,0.767496,-0.388502,...,-0.129511,-0.642084,-0.201161,-0.474606,-0.854537,0.201468,0.202296,-0.704604,-0.566913,0.635727

## <font color='red'>SET PARAMETERS</font>

### Cluster Selection for Visualization

Set these parameters to select the specific cluster to analyze:
- `CLUSTER_ID`: The cluster of interest to generate plots.

In [ ]:
CLUSTER_ID = None

In [ ]:
print(f"\n{'='*50}")
print(f"Analyzing Cluster {CLUSTER_ID}")
cluster_genes = cluster_df[cluster_df['cluster'] == CLUSTER_ID][config["aggregate"]["perturbation_name_col"]]
print(f"Genes in Cluster {CLUSTER_ID}:" ,", ".join(cluster_genes.unique()))
print(f"{'='*50}")

# Run differential analysis using robust z-score
diff_results = differential_analysis(
    feature_df=aggregate_df,  
    cluster_df=cluster_df,    
    cluster_id=CLUSTER_ID,
    control_type="nontargeting",  
    control_label=config["aggregate"]["control_key"],
    use_nonparametric=True,  
    normalize_method="robust_zscore"
)

# Display results in a more user-friendly format
print("\nTop Upregulated Features:")
up_df = diff_results['top_up'][['feature', 'robust_zscore', 'p_value', 'median_test', 'median_control']]
up_df = up_df.rename(columns={
    'robust_zscore': 'Z-score',
    'p_value': 'p-value',
    'median_test': 'Median (test)',
    'median_control': 'Median (control)'
})
display(up_df.style.format({
    'Z-score': '{:.2f}',
    'p-value': '{:.2e}',
    'Median (test)': '{:.3f}',
    'Median (control)': '{:.3f}'
}))

print("\nTop Downregulated Features:")
down_df = diff_results['top_down'][['feature', 'robust_zscore', 'p_value', 'median_test', 'median_control']]
down_df = down_df.rename(columns={
    'robust_zscore': 'Z-score',
    'p_value': 'p-value',
    'median_test': 'Median (test)',
    'median_control': 'Median (control)'
})
display(down_df.style.format({
    'Z-score': '{:.2f}',
    'p-value': '{:.2e}',
    'Median (test)': '{:.3f}',
    'Median (control)': '{:.3f}'
}))

## <font color='red'>SET PARAMETERS</font>

### Feature Selection for Visualization

Set these parameters to select the specific cluster to analyze:
- `FEATURES_TO_ANALYZE`: The features found in the differential analysis to generate plots for.
- `GENES_TO_LABEL`: The genes within the cluster to label on the plots.

In [ ]:
FEATURES_TO_ANALYZE = None
GENES_TO_LABEL = None

In [ ]:
# Create waterfall plots for selected features
print("\n--- Waterfall Plots for Selected Features ---")
for feature in FEATURES_TO_ANALYZE:
    print(f"\nPlotting: {feature}")
    waterfall_plot(
        feature_df=aggregate_df, 
        feature=feature,
        cluster_df=cluster_df,
        cluster_id=CLUSTER_ID,
        nontargeting_pattern=config["aggregate"]["control_key"],
        title=f"Cluster {CLUSTER_ID}: {feature}",
        label_genes=GENES_TO_LABEL
    )

# Create two-feature plots for combinations
print("\n--- Two-Feature Plots ---")
# Generate all unique pairs of features
feature_pairs = [(FEATURES_TO_ANALYZE[i], FEATURES_TO_ANALYZE[j]) 
                 for i in range(len(FEATURES_TO_ANALYZE)) 
                 for j in range(i+1, len(FEATURES_TO_ANALYZE))]

for feature1, feature2 in feature_pairs:
    print(f"\nPlotting: {feature1} vs {feature2}")
    two_feature_plot(
        feature_df=aggregate_df,
        x=feature1,
        y=feature2,
        cluster_df=cluster_df,
        cluster_id=CLUSTER_ID,
        nontargeting_pattern=config["aggregate"]["control_key"],
        title=f"Cluster {CLUSTER_ID}: {feature1} vs {feature2}",
        label_genes=GENES_TO_LABEL
    )

# Create heatmap with all differential features
print("\n--- Heatmap of Differential Features ---")
# Get top features from differential analysis
top_up = diff_results['top_up']['feature'].tolist() if not diff_results['top_up'].empty else []
top_down = diff_results['top_down']['feature'].tolist() if not diff_results['top_down'].empty else []
diff_features = top_up + top_down

fig, ax, heatmap_data = cluster_heatmap(
    feature_df=aggregate_df,
    cluster_df=cluster_df,
    cluster_ids=[CLUSTER_ID],
    features=diff_features,
    perturbation_name_col=config["aggregate"]["perturbation_name_col"],
    z_score="global",
    title=f"Cluster {CLUSTER_ID}: Top Differential Features",
)

# PHATE plot for the cluster
print("\n--- PHATE Plot for Cluster ---")
phate_fig = plot_phate_leiden_clusters(
    phate_leiden_clustering=cluster_df,
    perturbation_name_col=config["aggregate"]["perturbation_name_col"],
    control_key=config["aggregate"]["control_key"],
    clusters_of_interest=[CLUSTER_ID],
)

## Mozzarellm: LLM-based Gene Cluster Analysis

### Overview
[Mozzarellm](https://github.com/cheeseman-lab/mozzarellm) is a Python package that leverages Large Language Models (LLMs) to analyze gene clusters for pathway identification and novel gene discovery. This notebook guides you through the process of:

1. **Loading and reshaping gene cluster data** from your OPS screen
2. **Analyzing gene clusters with LLMs** to identify biological pathways
3. **Categorizing genes** as established pathway members, uncharacterized, or having novel potential roles
4. **Prioritizing candidates** for experimental validation

### Prerequisites

You need to install the mozzarellm package in your Brieflow environment:

```bash
pip install git+https://github.com/cheeseman-lab/mozzarellm.git
```

Mozzarellm requires API keys to access LLM services. You need at least one of these keys:

- **OpenAI API Key**: Required for GPT models (gpt-4o, gpt-4.5, etc.)
- **Anthropic API Key**: Required for Claude models (claude-3-7-sonnet, etc.)
- **Google API Key**: Required for Gemini models (gemini-2.0-pro, etc.)

These keys provide access to paid API services, and usage will incur costs based on the number of tokens processed. The cost per analysis varies by model but typically ranges from $0.01-$0.10 per cluster, depending on cluster size and model choice. For this reason, we only run these analyses on a specific chosen Leiden resolution, rather than across all of the generated possible resolutions.

In [26]:
import os
from mozzarellm import analyze_gene_clusters, reshape_to_clusters

In [ ]:
# Set API keys
os.environ["OPENAI_API_KEY"] = "your_openai_key_here"
os.environ["ANTHROPIC_API_KEY"] = "your_anthropic_key_here"  
os.environ["GOOGLE_API_KEY"] = "your_google_key_here"

In [28]:
RESULTS_DIR = cluster_path / "mozzarellm_analysis"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
print(f"Results will be saved to: {RESULTS_DIR}")

Results will be saved to: brieflow_output/cluster/DAPI_VIMENTIN_ITGB1/Interphase/15/mozzarellm_analysis

In [29]:
cluster_file = cluster_path / "phate_leiden_clustering.tsv"
cluster_df = pd.read_csv(cluster_file, sep="\t")
display(cluster_df)

,gene_symbol_0,cell_count,PHATE_0,PHATE_1,cluster,uniprot_entry,uniprot_function,uniprot_link,mean_potential_to_nontargeting,normalized_potential_to_nontargeting
0,RPL7,155,-0.117834,-0.016559,0,P18124,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/P18124/entry,7.411278,0.984631
1,RPL10,188,-0.113073,-0.015562,0,P27635,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/P27635/entry,7.111462,0.943287
2,RPL13A,208,-0.114349,-0.016143,0,P40429,Associated with ribosomes but is not required ...,https://www.uniprot.org/uniprotkb/P40429/entry,7.191240,0.954288
3,PEX13,290,-0.067548,-0.007744,0,Q92968,"Component of the PEX13-PEX14 docking complex, ...",https://www.uniprot.org/uniprotkb/Q92968/entry,4.263796,0.550602
4,BOP1,190,-0.088212,-0.010658,0,Q14137,"Component of the PeBoW complex, which is requi...",https://www.uniprot.org/uniprotkb/Q14137/entry,5.553396,0.728434
...,...,...,...,...,...,...,...,...,...,...
5291,MTCH2,263,0.000792,0.001325,508,Q9Y6C9,Protein insertase that mediates insertion of t...,https://www.uniprot.org/uniprotkb/Q9Y6C9/entry,0.337854,0.009226
5292,XRCC6,299,-0.000930,-0.011476,508,P12956,Single-stranded DNA-dependent ATP-dependent he...,https://www.uniprot.org/uniprotkb/P12956/entry,0.975402,0.097142
5293,COA3,128,0.002222,-0.000950,508,Q9Y2R0,Core component of the MITRAC (mitochondrial tr...,https://www.uniprot.org/uniprotkb/Q9Y2R0/entry,0.424310,0.021148
5294,CDC42,246,0.003742,-0.028796,508,P60953,Plasma membrane-associated small GTPase which ...,https://www.uniprot.org/uniprotkb/P60953/entry,1.981820,0.235924
5295,SON,158,0.003198,-0.029336,508,P18583,RNA-binding protein that acts as a mRNA splici...,https://www.uniprot.org/uniprotkb/P18583/entry,2.029083,0.242441

## <font color='red'>SET PARAMETERS</font>: 

### Data Reshaping

Configure gene clustering parameters:
- `GENE_COL`: Column containing gene identifiers
- `CLUSTER_COL`: Column containing cluster assignments
- `UNIPROT_COL`: Column with UniProt annotations

These parameters control how gene-level data is converted to cluster-level data. These are set to default values that will be established in upstream notebooks/snakemakes, and usually don't need to be manipulated.

In [30]:
GENE_COL = config["aggregate"]["perturbation_name_col"]
CLUSTER_COL = "cluster"
UNIPROT_COL = "uniprot_function"

In [31]:
llm_cluster_df, llm_uniprot_df = reshape_to_clusters(
    input_df=cluster_df, 
    gene_col=GENE_COL,
    cluster_col=CLUSTER_COL,
    uniprot_col=UNIPROT_COL, 
    verbose=True
)
display(llm_cluster_df)
display(llm_uniprot_df)

Using provided DataFrame with 5296 rows
Found 5296 genes across 509 clusters
Extracting gene features from uniprot_function column

     cluster_id                                              genes
0             0  RPL7;RPL10;RPL13A;PEX13;BOP1;RPL38;RPL6;RPL31;...
1             1  RPA1;DONSON;POLA2;H3-3A;FAM25C;AGAP6;PRIM1;CDC...
2             2  PRPF40A;UBL5;LSM5;LSM2;LSM6;TXNL4A;SMNDC1;MFAP...
3             3  RPS15;FBL;RPS3;RPS13;WDR43;RPS23;RPS7;RPS14;RP...
4             4  MED20;POLR2D;SUPT6H;MED17;POLR2G;GTF2B;MST1;ME...
..          ...                                                ...
504         504               NUF2;DHRS4;MIB1;VMA21;SUGP2;ATP6V0A2
505         505                     TRIR;CCND3;RANGAP1;POLD2;PPM1G
506         506  MRPS11;RNF115;TMEM242;KLF16;nontargeting_CGCAT...
507         507                        OGA;AKAP1;CCDC47;MPDU1;ICE2
508         508                         MTCH2;XRCC6;COA3;CDC42;SON

[509 rows x 2 columns]

     gene_symbol_0                                   uniprot_function
0             RPL7  Component of the large ribosomal subunit (PubM...
1            RPL10  Component of the large ribosomal subunit (PubM...
2           RPL13A  Associated with ribosomes but is not required ...
3            PEX13  Component of the PEX13-PEX14 docking complex, ...
4             BOP1  Component of the PeBoW complex, which is requi...
...            ...                                                ...
5291         MTCH2  Protein insertase that mediates insertion of t...
5292         XRCC6  Single-stranded DNA-dependent ATP-dependent he...
5293          COA3  Core component of the MITRAC (mitochondrial tr...
5294         CDC42  Plasma membrane-associated small GTPase which ...
5295           SON  RNA-binding protein that acts as a mRNA splici...

[5296 rows x 2 columns]

## <font color='red'>SET PARAMETERS</font>: 
### LLM Analysis Configuration

- `MODEL_NAME`: LLM to use for analysis. Usable models include:
  - OpenAI: `o4-mini`, `o3-mini`, `gpt-4.1`, `gpt-4o`
  - Anthropic: `claude-3-7-sonnet-20250219`, `claude-3-5-haiku-20241022`
  - Google: `gemini-2.5-pro-preview-03-25`, `gemini-2.5-flash-preview-04-17`
- `CONFIG_DICT`: Configuration file for the LLM model
- `SCREEN_CONTEXT`: Context for the analysis and how to evaluate _clusters_
- `CLUSTER_ANALYSIS_PROMPT`: Context for the analysis and how to evaluate _genes within clusters_

Mozzarellm includes optimized [configurations](https://github.com/cheeseman-lab/mozzarellm/blob/main/mozzarellm/configs.py) and [prompts](https://github.com/cheeseman-lab/mozzarellm/blob/main/mozzarellm/prompts.py) you can import as shown below.

Custom text files can also be used by setting `screen_context_path` and `cluster_analysis_prompt_path` parameters.

In [32]:
from mozzarellm.prompts import ROBUST_SCREEN_CONTEXT, ROBUST_CLUSTER_PROMPT
from mozzarellm.configs import DEFAULT_ANTHROPIC_CONFIG

In [33]:
# Set up model configs
MODEL_NAME = "claude-3-7-sonnet-20250219"
CONFIG_DICT = DEFAULT_ANTHROPIC_CONFIG
SCREEN_CONTEXT = ROBUST_SCREEN_CONTEXT
CLUSTER_ANALYSIS_PROMPT = ROBUST_CLUSTER_PROMPT

In [34]:
# Run LLM analysis
anthropic_results = analyze_gene_clusters(
    # Input data options
    input_df=llm_cluster_df,
    # Model and configuration
    model_name=MODEL_NAME,
    config_dict=CONFIG_DICT,
    # Analysis context and prompts
    screen_context=SCREEN_CONTEXT,
    cluster_analysis_prompt=CLUSTER_ANALYSIS_PROMPT,
    # Gene annotations
    gene_annotations_df=llm_uniprot_df,
    # Processing options
    batch_size=1,
    # Output options
    output_file=f"{RESULTS_DIR}/{MODEL_NAME}",
    save_outputs=True,
    outputs_to_generate=["json", "clusters", "flagged_genes"],
)

INFO:cluster_analysis_20250728_094741.log:Processing 509 clusters with model claude-3-7-sonnet-20250219

Loaded data with 509 rows and columns: ['cluster_id', 'genes']
Created annotations dictionary with 5296 entries from DataFrame

Processing clusters:   0%|          | 0/509 [00:00<?, ?it/s]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 60 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 0
Processing clusters:   0%|          | 1/509 [00:20<2:56:42, 20.87s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 49 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 1
Processing clusters:   0%|          | 2/509 [01:02<4:41:33, 33.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 46 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 2
Processing clusters:   1%|          | 3/509 [01:31<4:23:33, 31.25s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 38 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 3
Processing clusters:   1%|          | 4/509 [01:53<3:52:24, 27.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 36 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 4
INFO:cluster_analysis_20250728_094741.log:Saved progress for 5 clusters
Processing clusters:   1%|          | 5/509 [02:08<3:14:32, 23.16s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 36 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 5
Processing clusters:   1%|          | 6/509 [02:33<3:18:44, 23.71s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 34 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 6
Processing clusters:   1%|▏         | 7/509 [03:14<4:05:17, 29.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 33 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 7
Processing clusters:   2%|▏         | 8/509 [03:51<4:23:54, 31.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 32 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 8
Processing clusters:   2%|▏         | 9/509 [04:12<3:56:11, 28.34s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 29 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 9
INFO:cluster_analysis_20250728_094741.log:Saved progress for 10 clusters
Processing clusters:   2%|▏         | 10/509 [04:29<3:26:43, 24.86s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 28 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 10
Processing clusters:   2%|▏         | 11/509 [05:04<3:51:36, 27.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 27 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 11
Processing clusters:   2%|▏         | 12/509 [05:23<3:30:45, 25.44s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 26 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 12
Processing clusters:   3%|▎         | 13/509 [05:42<3:13:46, 23.44s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 23 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 13
Processing clusters:   3%|▎         | 14/509 [05:59<2:55:28, 21.27s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 20 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 14
INFO:cluster_analysis_20250728_094741.log:Saved progress for 15 clusters
Processing clusters:   3%|▎         | 15/509 [06:13<2:38:56, 19.30s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 20 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 15
Processing clusters:   3%|▎         | 16/509 [06:29<2:30:29, 18.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 19 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 16
Processing clusters:   3%|▎         | 17/509 [06:44<2:22:22, 17.36s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 18 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 17
Processing clusters:   4%|▎         | 18/509 [06:57<2:10:47, 15.98s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 17 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 18
Processing clusters:   4%|▎         | 19/509 [07:11<2:05:21, 15.35s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 16 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 19
INFO:cluster_analysis_20250728_094741.log:Saved progress for 20 clusters
Processing clusters:   4%|▍         | 20/509 [07:27<2:06:34, 15.53s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 16 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 20
Processing clusters:   4%|▍         | 21/509 [07:44<2:09:27, 15.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 16 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 21
Processing clusters:   4%|▍         | 22/509 [08:03<2:15:44, 16.72s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 16 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 22
Processing clusters:   5%|▍         | 23/509 [08:17<2:10:40, 16.13s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 16 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 23
Processing clusters:   5%|▍         | 24/509 [08:31<2:05:40, 15.55s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 16 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 24
INFO:cluster_analysis_20250728_094741.log:Saved progress for 25 clusters
Processing clusters:   5%|▍         | 25/509 [08:51<2:16:09, 16.88s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 15 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 25
Processing clusters:   5%|▌         | 26/509 [09:05<2:09:03, 16.03s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 15 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 26
Processing clusters:   5%|▌         | 27/509 [09:27<2:23:04, 17.81s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 15 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 27
Processing clusters:   6%|▌         | 28/509 [09:42<2:14:41, 16.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 15 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 28
Processing clusters:   6%|▌         | 29/509 [10:01<2:20:02, 17.50s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 15 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 29
INFO:cluster_analysis_20250728_094741.log:Saved progress for 30 clusters
Processing clusters:   6%|▌         | 30/509 [10:13<2:07:02, 15.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 30
Processing clusters:   6%|▌         | 31/509 [10:28<2:05:07, 15.71s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 31
Processing clusters:   6%|▋         | 32/509 [10:45<2:06:51, 15.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 32
Processing clusters:   6%|▋         | 33/509 [11:09<2:25:36, 18.35s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 33
Processing clusters:   7%|▋         | 34/509 [11:23<2:14:35, 17.00s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 34
INFO:cluster_analysis_20250728_094741.log:Saved progress for 35 clusters
Processing clusters:   7%|▋         | 35/509 [11:40<2:14:39, 17.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 35
Processing clusters:   7%|▋         | 36/509 [11:54<2:07:39, 16.19s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 36
Processing clusters:   7%|▋         | 37/509 [12:06<1:57:27, 14.93s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 37
Processing clusters:   7%|▋         | 38/509 [12:26<2:08:25, 16.36s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 38
Processing clusters:   8%|▊         | 39/509 [12:38<1:57:19, 14.98s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 39
INFO:cluster_analysis_20250728_094741.log:Saved progress for 40 clusters
Processing clusters:   8%|▊         | 40/509 [12:49<1:49:05, 13.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 40
Processing clusters:   8%|▊         | 41/509 [13:14<2:13:18, 17.09s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 41
Processing clusters:   8%|▊         | 42/509 [13:37<2:26:51, 18.87s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 14 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 42
Processing clusters:   8%|▊         | 43/509 [13:48<2:08:35, 16.56s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 43
Processing clusters:   9%|▊         | 44/509 [14:08<2:17:21, 17.72s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 44
INFO:cluster_analysis_20250728_094741.log:Saved progress for 45 clusters
Processing clusters:   9%|▉         | 45/509 [14:23<2:10:54, 16.93s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 45
Processing clusters:   9%|▉         | 46/509 [14:40<2:10:34, 16.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 46
Processing clusters:   9%|▉         | 47/509 [14:58<2:11:42, 17.11s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 47
Processing clusters:   9%|▉         | 48/509 [15:10<2:01:02, 15.75s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 48
Processing clusters:  10%|▉         | 49/509 [15:33<2:16:20, 17.78s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 49
INFO:cluster_analysis_20250728_094741.log:Saved progress for 50 clusters
Processing clusters:  10%|▉         | 50/509 [15:45<2:03:09, 16.10s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 50
Processing clusters:  10%|█         | 51/509 [16:06<2:14:20, 17.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 51
Processing clusters:  10%|█         | 52/509 [16:27<2:21:16, 18.55s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 52
Processing clusters:  10%|█         | 53/509 [16:41<2:11:51, 17.35s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 53
Processing clusters:  11%|█         | 54/509 [16:55<2:03:56, 16.34s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 54
INFO:cluster_analysis_20250728_094741.log:Saved progress for 55 clusters
Processing clusters:  11%|█         | 55/509 [17:13<2:07:32, 16.86s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 55
Processing clusters:  11%|█         | 56/509 [17:32<2:12:02, 17.49s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 56
Processing clusters:  11%|█         | 57/509 [17:47<2:05:21, 16.64s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 57
Processing clusters:  11%|█▏        | 58/509 [18:01<1:58:16, 15.74s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 58
Processing clusters:  12%|█▏        | 59/509 [18:16<1:56:57, 15.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 59
INFO:cluster_analysis_20250728_094741.log:Saved progress for 60 clusters
Processing clusters:  12%|█▏        | 60/509 [18:30<1:53:57, 15.23s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 60
Processing clusters:  12%|█▏        | 61/509 [18:43<1:48:22, 14.51s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 61
Processing clusters:  12%|█▏        | 62/509 [18:59<1:51:54, 15.02s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 62
Processing clusters:  12%|█▏        | 63/509 [19:22<2:08:19, 17.26s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 63
Processing clusters:  13%|█▎        | 64/509 [19:41<2:12:27, 17.86s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 64
INFO:cluster_analysis_20250728_094741.log:Saved progress for 65 clusters
Processing clusters:  13%|█▎        | 65/509 [19:58<2:09:58, 17.56s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 65
Processing clusters:  13%|█▎        | 66/509 [20:16<2:10:41, 17.70s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 66
Processing clusters:  13%|█▎        | 67/509 [20:30<2:02:31, 16.63s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 67
Processing clusters:  13%|█▎        | 68/509 [20:44<1:57:08, 15.94s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 68
Processing clusters:  14%|█▎        | 69/509 [21:07<2:10:34, 17.81s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 69
INFO:cluster_analysis_20250728_094741.log:Saved progress for 70 clusters
Processing clusters:  14%|█▍        | 70/509 [21:20<1:59:57, 16.39s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 70
Processing clusters:  14%|█▍        | 71/509 [21:31<1:47:24, 14.71s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 13 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 71
Processing clusters:  14%|█▍        | 72/509 [21:39<1:32:44, 12.73s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 72
Processing clusters:  14%|█▍        | 73/509 [21:53<1:35:25, 13.13s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 73
Processing clusters:  15%|█▍        | 74/509 [22:06<1:34:35, 13.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 74
INFO:cluster_analysis_20250728_094741.log:Saved progress for 75 clusters
Processing clusters:  15%|█▍        | 75/509 [22:18<1:33:44, 12.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 75
Processing clusters:  15%|█▍        | 76/509 [22:34<1:39:16, 13.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 76
Processing clusters:  15%|█▌        | 77/509 [22:50<1:43:32, 14.38s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 77
Processing clusters:  15%|█▌        | 78/509 [23:07<1:50:19, 15.36s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 78
Processing clusters:  16%|█▌        | 79/509 [23:19<1:41:53, 14.22s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 79
INFO:cluster_analysis_20250728_094741.log:Saved progress for 80 clusters
Processing clusters:  16%|█▌        | 80/509 [23:36<1:47:08, 14.98s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 80
Processing clusters:  16%|█▌        | 81/509 [23:49<1:43:12, 14.47s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 81
Processing clusters:  16%|█▌        | 82/509 [24:03<1:42:55, 14.46s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 82
Processing clusters:  16%|█▋        | 83/509 [24:21<1:50:10, 15.52s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 83
Processing clusters:  17%|█▋        | 84/509 [24:35<1:45:12, 14.85s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 84
INFO:cluster_analysis_20250728_094741.log:Saved progress for 85 clusters
Processing clusters:  17%|█▋        | 85/509 [24:48<1:40:47, 14.26s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 85
Processing clusters:  17%|█▋        | 86/509 [25:06<1:49:47, 15.57s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 86
Processing clusters:  17%|█▋        | 87/509 [25:27<2:00:39, 17.15s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 87
Processing clusters:  17%|█▋        | 88/509 [25:45<2:02:10, 17.41s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 88
Processing clusters:  17%|█▋        | 89/509 [25:59<1:54:36, 16.37s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 89
INFO:cluster_analysis_20250728_094741.log:Saved progress for 90 clusters
Processing clusters:  18%|█▊        | 90/509 [26:15<1:53:36, 16.27s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 90
Processing clusters:  18%|█▊        | 91/509 [26:34<1:58:14, 16.97s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 91
Processing clusters:  18%|█▊        | 92/509 [26:47<1:49:17, 15.73s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 92
Processing clusters:  18%|█▊        | 93/509 [27:00<1:45:16, 15.18s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 93
Processing clusters:  18%|█▊        | 94/509 [27:21<1:55:48, 16.74s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 94
INFO:cluster_analysis_20250728_094741.log:Saved progress for 95 clusters
Processing clusters:  19%|█▊        | 95/509 [27:34<1:48:31, 15.73s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 95
Processing clusters:  19%|█▉        | 96/509 [27:52<1:51:45, 16.24s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 96
Processing clusters:  19%|█▉        | 97/509 [28:06<1:47:58, 15.73s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 97
Processing clusters:  19%|█▉        | 98/509 [28:24<1:51:56, 16.34s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 98
Processing clusters:  19%|█▉        | 99/509 [28:38<1:47:56, 15.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 99
INFO:cluster_analysis_20250728_094741.log:Saved progress for 100 clusters
Processing clusters:  20%|█▉        | 100/509 [28:46<1:30:56, 13.34s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 100
Processing clusters:  20%|█▉        | 101/509 [29:00<1:32:29, 13.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 101
Processing clusters:  20%|██        | 102/509 [29:15<1:34:12, 13.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 102
Processing clusters:  20%|██        | 103/509 [29:28<1:33:21, 13.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 103
Processing clusters:  20%|██        | 104/509 [29:45<1:38:27, 14.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 104
INFO:cluster_analysis_20250728_094741.log:Saved progress for 105 clusters
Processing clusters:  21%|██        | 105/509 [29:58<1:36:18, 14.30s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 105
Processing clusters:  21%|██        | 106/509 [30:19<1:47:55, 16.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 12 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 106
Processing clusters:  21%|██        | 107/509 [30:31<1:39:54, 14.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 107
Processing clusters:  21%|██        | 108/509 [30:45<1:38:55, 14.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 108
Processing clusters:  21%|██▏       | 109/509 [31:00<1:37:46, 14.67s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 109
INFO:cluster_analysis_20250728_094741.log:Saved progress for 110 clusters
Processing clusters:  22%|██▏       | 110/509 [31:15<1:38:36, 14.83s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 110
Processing clusters:  22%|██▏       | 111/509 [31:26<1:30:53, 13.70s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 111
Processing clusters:  22%|██▏       | 112/509 [31:41<1:33:53, 14.19s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 112
Processing clusters:  22%|██▏       | 113/509 [31:58<1:37:37, 14.79s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 113
Processing clusters:  22%|██▏       | 114/509 [32:10<1:31:50, 13.95s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 114
INFO:cluster_analysis_20250728_094741.log:Saved progress for 115 clusters
Processing clusters:  23%|██▎       | 115/509 [32:25<1:35:25, 14.53s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 115
Processing clusters:  23%|██▎       | 116/509 [32:37<1:28:36, 13.53s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 116
Processing clusters:  23%|██▎       | 117/509 [32:50<1:27:15, 13.36s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 117
Processing clusters:  23%|██▎       | 118/509 [33:04<1:28:59, 13.66s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 118
Processing clusters:  23%|██▎       | 119/509 [33:17<1:28:02, 13.55s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 119
INFO:cluster_analysis_20250728_094741.log:Saved progress for 120 clusters
Processing clusters:  24%|██▎       | 120/509 [33:30<1:25:58, 13.26s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 120
Processing clusters:  24%|██▍       | 121/509 [33:38<1:16:00, 11.75s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 121
Processing clusters:  24%|██▍       | 122/509 [33:50<1:16:19, 11.83s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 122
Processing clusters:  24%|██▍       | 123/509 [34:10<1:30:52, 14.13s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 123
Processing clusters:  24%|██▍       | 124/509 [34:22<1:28:17, 13.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 124
INFO:cluster_analysis_20250728_094741.log:Saved progress for 125 clusters
Processing clusters:  25%|██▍       | 125/509 [34:39<1:34:02, 14.69s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 125
Processing clusters:  25%|██▍       | 126/509 [34:56<1:36:47, 15.16s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 126
Processing clusters:  25%|██▍       | 127/509 [35:13<1:41:06, 15.88s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 127
Processing clusters:  25%|██▌       | 128/509 [35:27<1:36:03, 15.13s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 128
Processing clusters:  25%|██▌       | 129/509 [35:46<1:44:24, 16.48s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 129
INFO:cluster_analysis_20250728_094741.log:Saved progress for 130 clusters
Processing clusters:  26%|██▌       | 130/509 [36:00<1:38:07, 15.54s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 130
Processing clusters:  26%|██▌       | 131/509 [36:13<1:34:01, 14.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 131
Processing clusters:  26%|██▌       | 132/509 [36:29<1:35:42, 15.23s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 132
Processing clusters:  26%|██▌       | 133/509 [36:41<1:29:52, 14.34s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 133
Processing clusters:  26%|██▋       | 134/509 [36:53<1:24:22, 13.50s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 134
INFO:cluster_analysis_20250728_094741.log:Saved progress for 135 clusters
Processing clusters:  27%|██▋       | 135/509 [37:08<1:26:44, 13.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 135
Processing clusters:  27%|██▋       | 136/509 [37:21<1:25:35, 13.77s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 136
Processing clusters:  27%|██▋       | 137/509 [37:36<1:26:37, 13.97s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 137
Processing clusters:  27%|██▋       | 138/509 [37:56<1:38:41, 15.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 138
Processing clusters:  27%|██▋       | 139/509 [38:11<1:36:57, 15.72s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 139
INFO:cluster_analysis_20250728_094741.log:Saved progress for 140 clusters
Processing clusters:  28%|██▊       | 140/509 [38:25<1:33:27, 15.20s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 140
Processing clusters:  28%|██▊       | 141/509 [38:37<1:26:26, 14.09s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 141
Processing clusters:  28%|██▊       | 142/509 [38:52<1:29:04, 14.56s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 142
Processing clusters:  28%|██▊       | 143/509 [39:09<1:32:57, 15.24s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 143
Processing clusters:  28%|██▊       | 144/509 [39:28<1:39:00, 16.28s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 144
INFO:cluster_analysis_20250728_094741.log:Saved progress for 145 clusters
Processing clusters:  28%|██▊       | 145/509 [39:42<1:35:24, 15.73s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 145
Processing clusters:  29%|██▊       | 146/509 [39:59<1:36:59, 16.03s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 146
Processing clusters:  29%|██▉       | 147/509 [40:15<1:37:17, 16.12s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 147
Processing clusters:  29%|██▉       | 148/509 [40:22<1:19:50, 13.27s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 148
Processing clusters:  29%|██▉       | 149/509 [40:34<1:16:48, 12.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 149
INFO:cluster_analysis_20250728_094741.log:Saved progress for 150 clusters
Processing clusters:  29%|██▉       | 150/509 [40:50<1:23:05, 13.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 150
Processing clusters:  30%|██▉       | 151/509 [41:11<1:34:35, 15.85s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 151
Processing clusters:  30%|██▉       | 152/509 [41:27<1:34:51, 15.94s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 152
Processing clusters:  30%|███       | 153/509 [41:39<1:28:01, 14.84s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 153
Processing clusters:  30%|███       | 154/509 [41:55<1:29:56, 15.20s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 154
INFO:cluster_analysis_20250728_094741.log:Saved progress for 155 clusters
Processing clusters:  30%|███       | 155/509 [42:09<1:28:11, 14.95s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 155
Processing clusters:  31%|███       | 156/509 [42:30<1:38:31, 16.75s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 156
Processing clusters:  31%|███       | 157/509 [42:49<1:41:54, 17.37s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 157
Processing clusters:  31%|███       | 158/509 [43:04<1:37:23, 16.65s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 158
Processing clusters:  31%|███       | 159/509 [43:16<1:28:11, 15.12s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 159
INFO:cluster_analysis_20250728_094741.log:Saved progress for 160 clusters
Processing clusters:  31%|███▏      | 160/509 [43:33<1:31:50, 15.79s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 160
Processing clusters:  32%|███▏      | 161/509 [43:46<1:25:51, 14.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 161
Processing clusters:  32%|███▏      | 162/509 [44:01<1:26:03, 14.88s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 162
Processing clusters:  32%|███▏      | 163/509 [44:17<1:28:36, 15.36s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 163
Processing clusters:  32%|███▏      | 164/509 [44:31<1:25:19, 14.84s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 11 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 164
INFO:cluster_analysis_20250728_094741.log:Saved progress for 165 clusters
Processing clusters:  32%|███▏      | 165/509 [44:46<1:26:05, 15.02s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 165
Processing clusters:  33%|███▎      | 166/509 [45:05<1:32:58, 16.26s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 166
Processing clusters:  33%|███▎      | 167/509 [45:20<1:30:14, 15.83s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 167
Processing clusters:  33%|███▎      | 168/509 [45:32<1:22:36, 14.53s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 168
Processing clusters:  33%|███▎      | 169/509 [45:45<1:19:44, 14.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 169
INFO:cluster_analysis_20250728_094741.log:Saved progress for 170 clusters
Processing clusters:  33%|███▎      | 170/509 [46:02<1:24:18, 14.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 170
Processing clusters:  34%|███▎      | 171/509 [46:14<1:19:15, 14.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 171
Processing clusters:  34%|███▍      | 172/509 [46:28<1:19:18, 14.12s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 172
Processing clusters:  34%|███▍      | 173/509 [46:39<1:13:35, 13.14s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 173
Processing clusters:  34%|███▍      | 174/509 [46:52<1:14:20, 13.31s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 174
INFO:cluster_analysis_20250728_094741.log:Saved progress for 175 clusters
Processing clusters:  34%|███▍      | 175/509 [47:11<1:23:31, 15.00s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 175
Processing clusters:  35%|███▍      | 176/509 [47:23<1:18:16, 14.10s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 176
Processing clusters:  35%|███▍      | 177/509 [47:41<1:23:16, 15.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 177
Processing clusters:  35%|███▍      | 178/509 [47:56<1:23:08, 15.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 178
Processing clusters:  35%|███▌      | 179/509 [48:08<1:17:42, 14.13s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 179
INFO:cluster_analysis_20250728_094741.log:Saved progress for 180 clusters
Processing clusters:  35%|███▌      | 180/509 [48:24<1:20:29, 14.68s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 180
Processing clusters:  36%|███▌      | 181/509 [48:41<1:23:55, 15.35s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 181
Processing clusters:  36%|███▌      | 182/509 [49:01<1:31:46, 16.84s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 182
Processing clusters:  36%|███▌      | 183/509 [49:19<1:32:47, 17.08s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 183
Processing clusters:  36%|███▌      | 184/509 [49:33<1:28:13, 16.29s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 184
INFO:cluster_analysis_20250728_094741.log:Saved progress for 185 clusters
Processing clusters:  36%|███▋      | 185/509 [49:46<1:23:15, 15.42s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 185
Processing clusters:  37%|███▋      | 186/509 [49:57<1:15:18, 13.99s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 186
Processing clusters:  37%|███▋      | 187/509 [50:14<1:20:02, 14.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 187
Processing clusters:  37%|███▋      | 188/509 [50:22<1:08:31, 12.81s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 188
Processing clusters:  37%|███▋      | 189/509 [50:35<1:08:11, 12.79s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 189
INFO:cluster_analysis_20250728_094741.log:Saved progress for 190 clusters
Processing clusters:  37%|███▋      | 190/509 [50:46<1:05:40, 12.35s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 190
Processing clusters:  38%|███▊      | 191/509 [50:58<1:05:19, 12.33s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 191
Processing clusters:  38%|███▊      | 192/509 [51:24<1:26:05, 16.29s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 192
Processing clusters:  38%|███▊      | 193/509 [51:37<1:19:57, 15.18s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 193
Processing clusters:  38%|███▊      | 194/509 [51:49<1:15:42, 14.42s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 194
INFO:cluster_analysis_20250728_094741.log:Saved progress for 195 clusters
Processing clusters:  38%|███▊      | 195/509 [52:01<1:11:48, 13.72s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 195
Processing clusters:  39%|███▊      | 196/509 [52:13<1:08:06, 13.06s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 196
Processing clusters:  39%|███▊      | 197/509 [52:27<1:09:13, 13.31s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 197
Processing clusters:  39%|███▉      | 198/509 [52:42<1:12:20, 13.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 198
Processing clusters:  39%|███▉      | 199/509 [52:59<1:16:33, 14.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 199
INFO:cluster_analysis_20250728_094741.log:Saved progress for 200 clusters
Processing clusters:  39%|███▉      | 200/509 [53:16<1:19:00, 15.34s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 200
Processing clusters:  39%|███▉      | 201/509 [53:32<1:20:11, 15.62s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 201
Processing clusters:  40%|███▉      | 202/509 [53:44<1:14:40, 14.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 202
Processing clusters:  40%|███▉      | 203/509 [53:56<1:10:12, 13.77s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 203
Processing clusters:  40%|████      | 204/509 [54:06<1:04:10, 12.63s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 204
INFO:cluster_analysis_20250728_094741.log:Saved progress for 205 clusters
Processing clusters:  40%|████      | 205/509 [54:23<1:11:37, 14.14s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 205
Processing clusters:  40%|████      | 206/509 [54:37<1:11:03, 14.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 206
Processing clusters:  41%|████      | 207/509 [54:53<1:13:29, 14.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 207
Processing clusters:  41%|████      | 208/509 [55:06<1:11:03, 14.16s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 208
Processing clusters:  41%|████      | 209/509 [55:22<1:12:39, 14.53s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 209
INFO:cluster_analysis_20250728_094741.log:Saved progress for 210 clusters
Processing clusters:  41%|████▏     | 210/509 [55:35<1:10:21, 14.12s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 210
Processing clusters:  41%|████▏     | 211/509 [55:58<1:23:54, 16.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 211
Processing clusters:  42%|████▏     | 212/509 [56:15<1:23:16, 16.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 212
Processing clusters:  42%|████▏     | 213/509 [56:27<1:15:58, 15.40s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 213
Processing clusters:  42%|████▏     | 214/509 [56:40<1:12:20, 14.71s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 214
INFO:cluster_analysis_20250728_094741.log:Saved progress for 215 clusters
Processing clusters:  42%|████▏     | 215/509 [56:54<1:10:57, 14.48s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 215
Processing clusters:  42%|████▏     | 216/509 [57:13<1:16:37, 15.69s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 216
Processing clusters:  43%|████▎     | 217/509 [57:26<1:13:12, 15.04s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 217
Processing clusters:  43%|████▎     | 218/509 [57:42<1:14:41, 15.40s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 218
Processing clusters:  43%|████▎     | 219/509 [57:58<1:14:50, 15.49s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 219
INFO:cluster_analysis_20250728_094741.log:Saved progress for 220 clusters
Processing clusters:  43%|████▎     | 220/509 [58:10<1:08:56, 14.31s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 220
Processing clusters:  43%|████▎     | 221/509 [58:29<1:15:21, 15.70s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 221
Processing clusters:  44%|████▎     | 222/509 [58:44<1:15:18, 15.74s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 222
Processing clusters:  44%|████▍     | 223/509 [58:59<1:13:28, 15.41s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 223
Processing clusters:  44%|████▍     | 224/509 [59:19<1:19:55, 16.83s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 224
INFO:cluster_analysis_20250728_094741.log:Saved progress for 225 clusters
Processing clusters:  44%|████▍     | 225/509 [59:34<1:16:09, 16.09s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 225
Processing clusters:  44%|████▍     | 226/509 [59:46<1:10:45, 15.00s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 226
Processing clusters:  45%|████▍     | 227/509 [1:00:04<1:14:45, 15.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 227
Processing clusters:  45%|████▍     | 228/509 [1:00:22<1:17:41, 16.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 228
Processing clusters:  45%|████▍     | 229/509 [1:00:39<1:18:11, 16.75s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 229
INFO:cluster_analysis_20250728_094741.log:Saved progress for 230 clusters
Processing clusters:  45%|████▌     | 230/509 [1:00:57<1:19:34, 17.11s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 230
Processing clusters:  45%|████▌     | 231/509 [1:01:11<1:14:22, 16.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 231
Processing clusters:  46%|████▌     | 232/509 [1:01:24<1:10:10, 15.20s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 232
Processing clusters:  46%|████▌     | 233/509 [1:01:36<1:05:45, 14.30s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 233
Processing clusters:  46%|████▌     | 234/509 [1:01:53<1:08:23, 14.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 234
INFO:cluster_analysis_20250728_094741.log:Saved progress for 235 clusters
Processing clusters:  46%|████▌     | 235/509 [1:02:08<1:08:23, 14.97s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 235
Processing clusters:  46%|████▋     | 236/509 [1:02:23<1:07:57, 14.93s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 236
Processing clusters:  47%|████▋     | 237/509 [1:02:34<1:02:19, 13.75s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 237
Processing clusters:  47%|████▋     | 238/509 [1:02:46<1:00:51, 13.47s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 238
Processing clusters:  47%|████▋     | 239/509 [1:02:59<59:27, 13.21s/it]  INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 239
INFO:cluster_analysis_20250728_094741.log:Saved progress for 240 clusters
Processing clusters:  47%|████▋     | 240/509 [1:03:13<1:00:50, 13.57s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 240
Processing clusters:  47%|████▋     | 241/509 [1:03:37<1:14:08, 16.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 241
Processing clusters:  48%|████▊     | 242/509 [1:03:55<1:15:33, 16.98s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 242
Processing clusters:  48%|████▊     | 243/509 [1:04:11<1:13:33, 16.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 243
Processing clusters:  48%|████▊     | 244/509 [1:04:26<1:11:42, 16.24s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 244
INFO:cluster_analysis_20250728_094741.log:Saved progress for 245 clusters
Processing clusters:  48%|████▊     | 245/509 [1:04:37<1:04:20, 14.62s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 245
Processing clusters:  48%|████▊     | 246/509 [1:04:48<59:14, 13.51s/it]  INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 246
Processing clusters:  49%|████▊     | 247/509 [1:05:02<59:56, 13.73s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 247
Processing clusters:  49%|████▊     | 248/509 [1:05:14<57:39, 13.26s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 248
Processing clusters:  49%|████▉     | 249/509 [1:05:26<54:58, 12.69s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 249
INFO:cluster_analysis_20250728_094741.log:Saved progress for 250 clusters
Processing clusters:  49%|████▉     | 250/509 [1:05:39<55:54, 12.95s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 250
Processing clusters:  49%|████▉     | 251/509 [1:05:54<58:37, 13.63s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 251
Processing clusters:  50%|████▉     | 252/509 [1:06:13<1:04:18, 15.02s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 10 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 252
Processing clusters:  50%|████▉     | 253/509 [1:06:31<1:07:50, 15.90s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 253
Processing clusters:  50%|████▉     | 254/509 [1:06:44<1:04:00, 15.06s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 254
INFO:cluster_analysis_20250728_094741.log:Saved progress for 255 clusters
Processing clusters:  50%|█████     | 255/509 [1:07:01<1:06:21, 15.68s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 255
Processing clusters:  50%|█████     | 256/509 [1:07:13<1:01:21, 14.55s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 256
Processing clusters:  50%|█████     | 257/509 [1:07:29<1:03:26, 15.10s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 257
Processing clusters:  51%|█████     | 258/509 [1:07:45<1:03:57, 15.29s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 258
Processing clusters:  51%|█████     | 259/509 [1:08:01<1:05:04, 15.62s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 259
INFO:cluster_analysis_20250728_094741.log:Saved progress for 260 clusters
Processing clusters:  51%|█████     | 260/509 [1:08:15<1:02:32, 15.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 260
Processing clusters:  51%|█████▏    | 261/509 [1:08:46<1:22:34, 19.98s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 261
Processing clusters:  51%|█████▏    | 262/509 [1:09:13<1:30:34, 22.00s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 262
Processing clusters:  52%|█████▏    | 263/509 [1:09:28<1:20:56, 19.74s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 263
Processing clusters:  52%|█████▏    | 264/509 [1:09:44<1:15:58, 18.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 264
INFO:cluster_analysis_20250728_094741.log:Saved progress for 265 clusters
Processing clusters:  52%|█████▏    | 265/509 [1:09:54<1:05:31, 16.11s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 265
Processing clusters:  52%|█████▏    | 266/509 [1:10:08<1:02:34, 15.45s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 266
Processing clusters:  52%|█████▏    | 267/509 [1:10:15<52:39, 13.06s/it]  INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 267
Processing clusters:  53%|█████▎    | 268/509 [1:10:33<57:49, 14.40s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 268
Processing clusters:  53%|█████▎    | 269/509 [1:10:45<55:14, 13.81s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 269
INFO:cluster_analysis_20250728_094741.log:Saved progress for 270 clusters
Processing clusters:  53%|█████▎    | 270/509 [1:10:56<50:49, 12.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 270
Processing clusters:  53%|█████▎    | 271/509 [1:11:11<53:25, 13.47s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 271
Processing clusters:  53%|█████▎    | 272/509 [1:11:27<56:06, 14.21s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 272
Processing clusters:  54%|█████▎    | 273/509 [1:11:37<51:59, 13.22s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 273
Processing clusters:  54%|█████▍    | 274/509 [1:11:51<52:34, 13.42s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 274
INFO:cluster_analysis_20250728_094741.log:Saved progress for 275 clusters
Processing clusters:  54%|█████▍    | 275/509 [1:12:08<56:02, 14.37s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 275
Processing clusters:  54%|█████▍    | 276/509 [1:12:26<1:00:12, 15.50s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 276
Processing clusters:  54%|█████▍    | 277/509 [1:12:39<57:15, 14.81s/it]  INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 277
Processing clusters:  55%|█████▍    | 278/509 [1:12:56<59:38, 15.49s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 278
Processing clusters:  55%|█████▍    | 279/509 [1:13:13<1:00:49, 15.87s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 279
INFO:cluster_analysis_20250728_094741.log:Saved progress for 280 clusters
Processing clusters:  55%|█████▌    | 280/509 [1:13:31<1:03:18, 16.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 280
Processing clusters:  55%|█████▌    | 281/509 [1:13:41<55:31, 14.61s/it]  INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 281
Processing clusters:  55%|█████▌    | 282/509 [1:13:54<53:06, 14.04s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 282
Processing clusters:  56%|█████▌    | 283/509 [1:14:10<55:00, 14.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 283
Processing clusters:  56%|█████▌    | 284/509 [1:14:24<54:31, 14.54s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 284
INFO:cluster_analysis_20250728_094741.log:Saved progress for 285 clusters
Processing clusters:  56%|█████▌    | 285/509 [1:14:37<51:34, 13.81s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 285
Processing clusters:  56%|█████▌    | 286/509 [1:14:51<52:16, 14.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 286
Processing clusters:  56%|█████▋    | 287/509 [1:15:11<58:54, 15.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 287
Processing clusters:  57%|█████▋    | 288/509 [1:15:27<57:54, 15.72s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 288
Processing clusters:  57%|█████▋    | 289/509 [1:15:41<55:35, 15.16s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 289
INFO:cluster_analysis_20250728_094741.log:Saved progress for 290 clusters
Processing clusters:  57%|█████▋    | 290/509 [1:15:56<55:57, 15.33s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 290
Processing clusters:  57%|█████▋    | 291/509 [1:16:10<53:34, 14.75s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 291
Processing clusters:  57%|█████▋    | 292/509 [1:16:22<51:12, 14.16s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 292
Processing clusters:  58%|█████▊    | 293/509 [1:16:39<53:08, 14.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 293
Processing clusters:  58%|█████▊    | 294/509 [1:16:53<52:53, 14.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 294
INFO:cluster_analysis_20250728_094741.log:Saved progress for 295 clusters
Processing clusters:  58%|█████▊    | 295/509 [1:17:11<55:54, 15.67s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 295
Processing clusters:  58%|█████▊    | 296/509 [1:17:23<51:20, 14.46s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 296
Processing clusters:  58%|█████▊    | 297/509 [1:17:38<51:49, 14.67s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 297
Processing clusters:  59%|█████▊    | 298/509 [1:17:50<48:48, 13.88s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 298
Processing clusters:  59%|█████▊    | 299/509 [1:18:04<48:34, 13.88s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 299
INFO:cluster_analysis_20250728_094741.log:Saved progress for 300 clusters
Processing clusters:  59%|█████▉    | 300/509 [1:18:20<51:06, 14.67s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 300
Processing clusters:  59%|█████▉    | 301/509 [1:18:33<48:47, 14.08s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 301
Processing clusters:  59%|█████▉    | 302/509 [1:18:45<46:13, 13.40s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 302
Processing clusters:  60%|█████▉    | 303/509 [1:18:52<39:37, 11.54s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 303
Processing clusters:  60%|█████▉    | 304/509 [1:19:07<42:27, 12.43s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 304
INFO:cluster_analysis_20250728_094741.log:Saved progress for 305 clusters
Processing clusters:  60%|█████▉    | 305/509 [1:19:21<44:18, 13.03s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 305
Processing clusters:  60%|██████    | 306/509 [1:19:36<46:24, 13.72s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 306
Processing clusters:  60%|██████    | 307/509 [1:19:51<47:15, 14.04s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 307
Processing clusters:  61%|██████    | 308/509 [1:20:07<49:02, 14.64s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 308
Processing clusters:  61%|██████    | 309/509 [1:20:22<48:36, 14.58s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 309
INFO:cluster_analysis_20250728_094741.log:Saved progress for 310 clusters
Processing clusters:  61%|██████    | 310/509 [1:20:36<48:37, 14.66s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 310
Processing clusters:  61%|██████    | 311/509 [1:20:54<50:44, 15.38s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 311
Processing clusters:  61%|██████▏   | 312/509 [1:21:06<48:03, 14.64s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 312
Processing clusters:  61%|██████▏   | 313/509 [1:21:18<44:38, 13.66s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 313
Processing clusters:  62%|██████▏   | 314/509 [1:21:33<46:11, 14.21s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 314
INFO:cluster_analysis_20250728_094741.log:Saved progress for 315 clusters
Processing clusters:  62%|██████▏   | 315/509 [1:21:52<49:49, 15.41s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 315
Processing clusters:  62%|██████▏   | 316/509 [1:22:18<59:54, 18.63s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 316
Processing clusters:  62%|██████▏   | 317/509 [1:22:32<55:51, 17.45s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 317
Processing clusters:  62%|██████▏   | 318/509 [1:22:48<54:16, 17.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 318
Processing clusters:  63%|██████▎   | 319/509 [1:23:04<52:10, 16.47s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 319
INFO:cluster_analysis_20250728_094741.log:Saved progress for 320 clusters
Processing clusters:  63%|██████▎   | 320/509 [1:23:20<51:40, 16.40s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 320
Processing clusters:  63%|██████▎   | 321/509 [1:23:36<50:44, 16.19s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 321
Processing clusters:  63%|██████▎   | 322/509 [1:23:49<48:06, 15.44s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 322
Processing clusters:  63%|██████▎   | 323/509 [1:24:03<46:08, 14.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 323
Processing clusters:  64%|██████▎   | 324/509 [1:24:15<43:12, 14.01s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 324
INFO:cluster_analysis_20250728_094741.log:Saved progress for 325 clusters
Processing clusters:  64%|██████▍   | 325/509 [1:24:24<38:19, 12.50s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 325
Processing clusters:  64%|██████▍   | 326/509 [1:24:39<40:36, 13.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 326
Processing clusters:  64%|██████▍   | 327/509 [1:24:55<42:37, 14.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 327
Processing clusters:  64%|██████▍   | 328/509 [1:25:07<40:27, 13.41s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 328
Processing clusters:  65%|██████▍   | 329/509 [1:25:19<39:05, 13.03s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 329
INFO:cluster_analysis_20250728_094741.log:Saved progress for 330 clusters
Processing clusters:  65%|██████▍   | 330/509 [1:25:32<39:24, 13.21s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 330
Processing clusters:  65%|██████▌   | 331/509 [1:25:45<38:13, 12.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 331
Processing clusters:  65%|██████▌   | 332/509 [1:26:01<41:34, 14.09s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 332
Processing clusters:  65%|██████▌   | 333/509 [1:26:18<43:45, 14.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 333
Processing clusters:  66%|██████▌   | 334/509 [1:26:28<38:30, 13.20s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 334
INFO:cluster_analysis_20250728_094741.log:Saved progress for 335 clusters
Processing clusters:  66%|██████▌   | 335/509 [1:26:39<36:47, 12.69s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 335
Processing clusters:  66%|██████▌   | 336/509 [1:26:58<41:40, 14.45s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 336
Processing clusters:  66%|██████▌   | 337/509 [1:27:12<41:08, 14.35s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 337
Processing clusters:  66%|██████▋   | 338/509 [1:27:25<40:13, 14.11s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 338
Processing clusters:  67%|██████▋   | 339/509 [1:27:40<40:20, 14.24s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 339
INFO:cluster_analysis_20250728_094741.log:Saved progress for 340 clusters
Processing clusters:  67%|██████▋   | 340/509 [1:27:56<42:03, 14.93s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 340
Processing clusters:  67%|██████▋   | 341/509 [1:28:10<40:50, 14.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 341
Processing clusters:  67%|██████▋   | 342/509 [1:28:26<41:56, 15.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 342
Processing clusters:  67%|██████▋   | 343/509 [1:28:43<42:57, 15.53s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 343
Processing clusters:  68%|██████▊   | 344/509 [1:29:01<44:42, 16.26s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 344
INFO:cluster_analysis_20250728_094741.log:Saved progress for 345 clusters
Processing clusters:  68%|██████▊   | 345/509 [1:29:16<43:30, 15.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 345
Processing clusters:  68%|██████▊   | 346/509 [1:29:31<42:52, 15.78s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 346
Processing clusters:  68%|██████▊   | 347/509 [1:29:47<42:43, 15.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 347
Processing clusters:  68%|██████▊   | 348/509 [1:30:01<41:01, 15.29s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 348
Processing clusters:  69%|██████▊   | 349/509 [1:30:14<38:57, 14.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 349
INFO:cluster_analysis_20250728_094741.log:Saved progress for 350 clusters
Processing clusters:  69%|██████▉   | 350/509 [1:30:33<41:30, 15.66s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 9 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 350
Processing clusters:  69%|██████▉   | 351/509 [1:30:39<34:08, 12.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 351
Processing clusters:  69%|██████▉   | 352/509 [1:30:43<26:57, 10.30s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 352
Processing clusters:  69%|██████▉   | 353/509 [1:30:58<29:55, 11.51s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 353
Processing clusters:  70%|██████▉   | 354/509 [1:31:14<33:50, 13.10s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 354
INFO:cluster_analysis_20250728_094741.log:Saved progress for 355 clusters
Processing clusters:  70%|██████▉   | 355/509 [1:31:32<37:04, 14.45s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 355
Processing clusters:  70%|██████▉   | 356/509 [1:31:43<33:54, 13.30s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 356
Processing clusters:  70%|███████   | 357/509 [1:31:55<32:54, 12.99s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 357
Processing clusters:  70%|███████   | 358/509 [1:32:04<29:35, 11.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 358
Processing clusters:  71%|███████   | 359/509 [1:32:15<28:42, 11.48s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 359
INFO:cluster_analysis_20250728_094741.log:Saved progress for 360 clusters
Processing clusters:  71%|███████   | 360/509 [1:32:30<31:45, 12.79s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 360
Processing clusters:  71%|███████   | 361/509 [1:32:43<31:29, 12.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 361
Processing clusters:  71%|███████   | 362/509 [1:32:57<32:06, 13.11s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 362
Processing clusters:  71%|███████▏  | 363/509 [1:33:04<27:24, 11.26s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 363
Processing clusters:  72%|███████▏  | 364/509 [1:33:17<28:13, 11.68s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 364
INFO:cluster_analysis_20250728_094741.log:Saved progress for 365 clusters
Processing clusters:  72%|███████▏  | 365/509 [1:33:30<29:00, 12.09s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 365
Processing clusters:  72%|███████▏  | 366/509 [1:33:40<27:46, 11.65s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 366
Processing clusters:  72%|███████▏  | 367/509 [1:33:54<28:52, 12.20s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 367
Processing clusters:  72%|███████▏  | 368/509 [1:34:10<31:13, 13.29s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 368
Processing clusters:  72%|███████▏  | 369/509 [1:34:23<30:47, 13.20s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 369
INFO:cluster_analysis_20250728_094741.log:Saved progress for 370 clusters
Processing clusters:  73%|███████▎  | 370/509 [1:34:34<29:06, 12.57s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 370
Processing clusters:  73%|███████▎  | 371/509 [1:34:44<27:06, 11.79s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 371
Processing clusters:  73%|███████▎  | 372/509 [1:34:59<29:13, 12.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 372
Processing clusters:  73%|███████▎  | 373/509 [1:35:13<30:08, 13.30s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 373
Processing clusters:  73%|███████▎  | 374/509 [1:35:26<29:16, 13.01s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 374
INFO:cluster_analysis_20250728_094741.log:Saved progress for 375 clusters
Processing clusters:  74%|███████▎  | 375/509 [1:35:41<30:30, 13.66s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 375
Processing clusters:  74%|███████▍  | 376/509 [1:35:57<32:06, 14.48s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 376
Processing clusters:  74%|███████▍  | 377/509 [1:36:09<30:19, 13.78s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 377
Processing clusters:  74%|███████▍  | 378/509 [1:36:23<29:43, 13.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 378
Processing clusters:  74%|███████▍  | 379/509 [1:36:34<27:52, 12.87s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 379
INFO:cluster_analysis_20250728_094741.log:Saved progress for 380 clusters
Processing clusters:  75%|███████▍  | 380/509 [1:36:50<30:07, 14.01s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 380
Processing clusters:  75%|███████▍  | 381/509 [1:37:05<30:32, 14.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 381
Processing clusters:  75%|███████▌  | 382/509 [1:37:20<30:40, 14.50s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 382
Processing clusters:  75%|███████▌  | 383/509 [1:37:32<28:45, 13.70s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 383
Processing clusters:  75%|███████▌  | 384/509 [1:37:45<28:13, 13.55s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 384
INFO:cluster_analysis_20250728_094741.log:Saved progress for 385 clusters
Processing clusters:  76%|███████▌  | 385/509 [1:37:54<25:00, 12.10s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 385
Processing clusters:  76%|███████▌  | 386/509 [1:38:01<21:49, 10.64s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 386
Processing clusters:  76%|███████▌  | 387/509 [1:38:15<23:27, 11.54s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 387
Processing clusters:  76%|███████▌  | 388/509 [1:38:28<24:02, 11.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 388
Processing clusters:  76%|███████▋  | 389/509 [1:38:40<23:48, 11.90s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 389
INFO:cluster_analysis_20250728_094741.log:Saved progress for 390 clusters
Processing clusters:  77%|███████▋  | 390/509 [1:38:52<24:08, 12.17s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 390
Processing clusters:  77%|███████▋  | 391/509 [1:39:04<23:14, 11.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 391
Processing clusters:  77%|███████▋  | 392/509 [1:39:18<24:44, 12.69s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 392
Processing clusters:  77%|███████▋  | 393/509 [1:39:32<25:11, 13.03s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 393
Processing clusters:  77%|███████▋  | 394/509 [1:39:49<27:28, 14.33s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 394
INFO:cluster_analysis_20250728_094741.log:Saved progress for 395 clusters
Processing clusters:  78%|███████▊  | 395/509 [1:40:11<31:34, 16.62s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 395
Processing clusters:  78%|███████▊  | 396/509 [1:40:28<31:23, 16.67s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 396
Processing clusters:  78%|███████▊  | 397/509 [1:40:40<28:18, 15.17s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 397
Processing clusters:  78%|███████▊  | 398/509 [1:40:53<27:01, 14.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 398
Processing clusters:  78%|███████▊  | 399/509 [1:41:10<27:52, 15.21s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 399
INFO:cluster_analysis_20250728_094741.log:Saved progress for 400 clusters
Processing clusters:  79%|███████▊  | 400/509 [1:41:25<27:31, 15.15s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 400
Processing clusters:  79%|███████▉  | 401/509 [1:41:37<25:58, 14.43s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 401
Processing clusters:  79%|███████▉  | 402/509 [1:41:50<24:31, 13.75s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 402
Processing clusters:  79%|███████▉  | 403/509 [1:42:02<23:36, 13.36s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 403
Processing clusters:  79%|███████▉  | 404/509 [1:42:19<25:22, 14.50s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 404
INFO:cluster_analysis_20250728_094741.log:Saved progress for 405 clusters
Processing clusters:  80%|███████▉  | 405/509 [1:42:33<24:50, 14.33s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 405
Processing clusters:  80%|███████▉  | 406/509 [1:42:46<24:02, 14.00s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 406
Processing clusters:  80%|███████▉  | 407/509 [1:43:04<25:35, 15.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 407
Processing clusters:  80%|████████  | 408/509 [1:43:17<24:05, 14.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 408
Processing clusters:  80%|████████  | 409/509 [1:43:29<23:06, 13.86s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 409
INFO:cluster_analysis_20250728_094741.log:Saved progress for 410 clusters
Processing clusters:  81%|████████  | 410/509 [1:43:48<25:13, 15.29s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 410
Processing clusters:  81%|████████  | 411/509 [1:44:02<24:19, 14.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 411
Processing clusters:  81%|████████  | 412/509 [1:44:13<22:20, 13.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 412
Processing clusters:  81%|████████  | 413/509 [1:44:30<23:42, 14.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 413
Processing clusters:  81%|████████▏ | 414/509 [1:44:48<24:57, 15.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 414
INFO:cluster_analysis_20250728_094741.log:Saved progress for 415 clusters
Processing clusters:  82%|████████▏ | 415/509 [1:45:03<24:08, 15.41s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 415
Processing clusters:  82%|████████▏ | 416/509 [1:45:19<23:59, 15.48s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 416
Processing clusters:  82%|████████▏ | 417/509 [1:45:25<19:21, 12.62s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 417
Processing clusters:  82%|████████▏ | 418/509 [1:45:38<19:34, 12.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 418
Processing clusters:  82%|████████▏ | 419/509 [1:45:53<20:19, 13.55s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 419
INFO:cluster_analysis_20250728_094741.log:Saved progress for 420 clusters
Processing clusters:  83%|████████▎ | 420/509 [1:46:06<19:45, 13.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 420
Processing clusters:  83%|████████▎ | 421/509 [1:46:20<19:49, 13.51s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 421
Processing clusters:  83%|████████▎ | 422/509 [1:46:34<19:38, 13.55s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 422
Processing clusters:  83%|████████▎ | 423/509 [1:46:48<19:51, 13.86s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 423
Processing clusters:  83%|████████▎ | 424/509 [1:47:05<20:43, 14.63s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 424
INFO:cluster_analysis_20250728_094741.log:Saved progress for 425 clusters
Processing clusters:  83%|████████▎ | 425/509 [1:47:19<20:17, 14.49s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 425
Processing clusters:  84%|████████▎ | 426/509 [1:47:33<19:57, 14.43s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 426
Processing clusters:  84%|████████▍ | 427/509 [1:47:48<20:01, 14.65s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 427
Processing clusters:  84%|████████▍ | 428/509 [1:48:04<20:16, 15.02s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 428
Processing clusters:  84%|████████▍ | 429/509 [1:48:13<17:36, 13.21s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 8 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 429
INFO:cluster_analysis_20250728_094741.log:Saved progress for 430 clusters
Processing clusters:  84%|████████▍ | 430/509 [1:48:28<17:54, 13.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 430
Processing clusters:  85%|████████▍ | 431/509 [1:48:40<17:02, 13.11s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 431
Processing clusters:  85%|████████▍ | 432/509 [1:48:52<16:34, 12.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 432
Processing clusters:  85%|████████▌ | 433/509 [1:49:04<16:11, 12.78s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 433
Processing clusters:  85%|████████▌ | 434/509 [1:49:18<16:08, 12.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 434
INFO:cluster_analysis_20250728_094741.log:Saved progress for 435 clusters
Processing clusters:  85%|████████▌ | 435/509 [1:49:37<18:18, 14.84s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 435
Processing clusters:  86%|████████▌ | 436/509 [1:49:52<18:16, 15.02s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 436
Processing clusters:  86%|████████▌ | 437/509 [1:50:05<17:16, 14.40s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 437
Processing clusters:  86%|████████▌ | 438/509 [1:50:25<18:48, 15.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 438
Processing clusters:  86%|████████▌ | 439/509 [1:50:35<16:42, 14.33s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 439
INFO:cluster_analysis_20250728_094741.log:Saved progress for 440 clusters
Processing clusters:  86%|████████▋ | 440/509 [1:50:49<16:21, 14.23s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 440
Processing clusters:  87%|████████▋ | 441/509 [1:51:02<15:40, 13.83s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 441
Processing clusters:  87%|████████▋ | 442/509 [1:51:16<15:14, 13.66s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 442
Processing clusters:  87%|████████▋ | 443/509 [1:51:27<14:24, 13.10s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 443
Processing clusters:  87%|████████▋ | 444/509 [1:51:40<13:57, 12.89s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 444
INFO:cluster_analysis_20250728_094741.log:Saved progress for 445 clusters
Processing clusters:  87%|████████▋ | 445/509 [1:51:50<12:44, 11.94s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 445
Processing clusters:  88%|████████▊ | 446/509 [1:52:04<13:27, 12.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 446
Processing clusters:  88%|████████▊ | 447/509 [1:52:17<13:12, 12.78s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 447
Processing clusters:  88%|████████▊ | 448/509 [1:52:30<13:10, 12.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 448
Processing clusters:  88%|████████▊ | 449/509 [1:52:43<12:55, 12.92s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 449
INFO:cluster_analysis_20250728_094741.log:Saved progress for 450 clusters
Processing clusters:  88%|████████▊ | 450/509 [1:52:57<13:04, 13.29s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 450
Processing clusters:  89%|████████▊ | 451/509 [1:53:14<13:50, 14.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 451
Processing clusters:  89%|████████▉ | 452/509 [1:53:29<13:39, 14.37s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 452
Processing clusters:  89%|████████▉ | 453/509 [1:53:41<12:53, 13.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 453
Processing clusters:  89%|████████▉ | 454/509 [1:53:57<13:04, 14.27s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 454
INFO:cluster_analysis_20250728_094741.log:Saved progress for 455 clusters
Processing clusters:  89%|████████▉ | 455/509 [1:54:11<12:59, 14.43s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 455
Processing clusters:  90%|████████▉ | 456/509 [1:54:20<11:16, 12.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 456
Processing clusters:  90%|████████▉ | 457/509 [1:54:33<11:05, 12.80s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 457
Processing clusters:  90%|████████▉ | 458/509 [1:54:42<09:45, 11.49s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 458
Processing clusters:  90%|█████████ | 459/509 [1:54:55<10:06, 12.14s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 459
INFO:cluster_analysis_20250728_094741.log:Saved progress for 460 clusters
Processing clusters:  90%|█████████ | 460/509 [1:55:05<09:14, 11.32s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 460
Processing clusters:  91%|█████████ | 461/509 [1:55:18<09:37, 12.03s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 461
Processing clusters:  91%|█████████ | 462/509 [1:55:36<10:39, 13.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 462
Processing clusters:  91%|█████████ | 463/509 [1:55:52<11:02, 14.40s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 463
Processing clusters:  91%|█████████ | 464/509 [1:55:58<09:02, 12.05s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 464
INFO:cluster_analysis_20250728_094741.log:Saved progress for 465 clusters
Processing clusters:  91%|█████████▏| 465/509 [1:56:13<09:26, 12.87s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 465
Processing clusters:  92%|█████████▏| 466/509 [1:56:31<10:11, 14.21s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 466
Processing clusters:  92%|█████████▏| 467/509 [1:56:37<08:23, 11.99s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 467
Processing clusters:  92%|█████████▏| 468/509 [1:56:47<07:48, 11.42s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 468
Processing clusters:  92%|█████████▏| 469/509 [1:57:03<08:31, 12.79s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 469
INFO:cluster_analysis_20250728_094741.log:Saved progress for 470 clusters
Processing clusters:  92%|█████████▏| 470/509 [1:57:16<08:12, 12.63s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 470
Processing clusters:  93%|█████████▎| 471/509 [1:57:21<06:37, 10.47s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 471
Processing clusters:  93%|█████████▎| 472/509 [1:57:35<07:07, 11.57s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 472
Processing clusters:  93%|█████████▎| 473/509 [1:57:48<07:05, 11.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 473
Processing clusters:  93%|█████████▎| 474/509 [1:58:03<07:26, 12.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 474
INFO:cluster_analysis_20250728_094741.log:Saved progress for 475 clusters
Processing clusters:  93%|█████████▎| 475/509 [1:58:15<07:08, 12.61s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 475
Processing clusters:  94%|█████████▎| 476/509 [1:58:27<06:50, 12.44s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 476
Processing clusters:  94%|█████████▎| 477/509 [1:58:40<06:47, 12.73s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 477
Processing clusters:  94%|█████████▍| 478/509 [1:58:56<07:01, 13.59s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 478
Processing clusters:  94%|█████████▍| 479/509 [1:59:08<06:38, 13.28s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 479
INFO:cluster_analysis_20250728_094741.log:Saved progress for 480 clusters
Processing clusters:  94%|█████████▍| 480/509 [1:59:17<05:44, 11.88s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 480
Processing clusters:  94%|█████████▍| 481/509 [1:59:31<05:53, 12.62s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 481
Processing clusters:  95%|█████████▍| 482/509 [1:59:42<05:25, 12.07s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 7 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 482
Processing clusters:  95%|█████████▍| 483/509 [1:59:58<05:40, 13.09s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 483
Processing clusters:  95%|█████████▌| 484/509 [2:00:14<05:48, 13.95s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 484
INFO:cluster_analysis_20250728_094741.log:Saved progress for 485 clusters
Processing clusters:  95%|█████████▌| 485/509 [2:00:30<05:54, 14.76s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 485
Processing clusters:  95%|█████████▌| 486/509 [2:00:42<05:21, 13.99s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 486
Processing clusters:  96%|█████████▌| 487/509 [2:00:48<04:12, 11.49s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 487
Processing clusters:  96%|█████████▌| 488/509 [2:01:03<04:21, 12.47s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 488
Processing clusters:  96%|█████████▌| 489/509 [2:01:15<04:08, 12.44s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 489
INFO:cluster_analysis_20250728_094741.log:Saved progress for 490 clusters
Processing clusters:  96%|█████████▋| 490/509 [2:01:27<03:50, 12.12s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 490
Processing clusters:  96%|█████████▋| 491/509 [2:01:39<03:42, 12.34s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 491
Processing clusters:  97%|█████████▋| 492/509 [2:01:57<03:56, 13.91s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 492
Processing clusters:  97%|█████████▋| 493/509 [2:02:07<03:21, 12.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 493
Processing clusters:  97%|█████████▋| 494/509 [2:02:18<03:01, 12.12s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 494
INFO:cluster_analysis_20250728_094741.log:Saved progress for 495 clusters
Processing clusters:  97%|█████████▋| 495/509 [2:02:29<02:48, 12.06s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 495
Processing clusters:  97%|█████████▋| 496/509 [2:02:44<02:45, 12.71s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 496
Processing clusters:  98%|█████████▊| 497/509 [2:02:58<02:36, 13.08s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 497
Processing clusters:  98%|█████████▊| 498/509 [2:03:10<02:22, 12.98s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 498
Processing clusters:  98%|█████████▊| 499/509 [2:03:20<01:59, 11.96s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 499
INFO:cluster_analysis_20250728_094741.log:Saved progress for 500 clusters
Processing clusters:  98%|█████████▊| 500/509 [2:03:32<01:46, 11.84s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 500
Processing clusters:  98%|█████████▊| 501/509 [2:03:44<01:36, 12.04s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 501
Processing clusters:  99%|█████████▊| 502/509 [2:03:56<01:25, 12.16s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 502
Processing clusters:  99%|█████████▉| 503/509 [2:04:09<01:13, 12.20s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 503
Processing clusters:  99%|█████████▉| 504/509 [2:04:22<01:02, 12.60s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 6 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 504
INFO:cluster_analysis_20250728_094741.log:Saved progress for 505 clusters
Processing clusters:  99%|█████████▉| 505/509 [2:04:36<00:51, 12.82s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 5 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 505
Processing clusters:  99%|█████████▉| 506/509 [2:04:49<00:39, 13.03s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 5 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 506
Processing clusters: 100%|█████████▉| 507/509 [2:04:59<00:24, 12.10s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 5 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 507
Processing clusters: 100%|█████████▉| 508/509 [2:05:10<00:11, 11.69s/it]INFO:cluster_analysis_20250728_094741.log:Using Anthropic Claude API

Using provided template string
Appending output format instructions to template
Added 5 gene feature descriptions to prompt

INFO:cluster_analysis_20250728_094741.log:Anthropic API call successful: model=claude-3-7-sonnet-20250219
INFO:cluster_analysis_20250728_094741.log:Success for cluster 508
Processing clusters: 100%|██████████| 509/509 [2:05:21<00:00, 14.78s/it]
INFO:cluster_analysis_20250728_094741.log:Completed analysis for 509 clusters with data saved to disk

## Cluster overlap analysis

In [21]:
import pandas as pd
import numpy as np
from collections import Counter

def analyze_cluster_novelty(clustering_df, aconcagua_df, enrichment_df, mozzarellm_df, 
                           gene_col='gene_symbol_0', new_cluster_col='cluster', old_cluster_col='cluster',
                           jaccard_threshold=0.3, target_keywords=None):
    """
    
    # Default keywords for kinetochore/CENPT screen
    if target_keywords is None:
        target_keywords = ['kinetochore', 'centromere', 'chromosome', 'mitosis', 'spindle', 'CENP', 
                          'segregation', 'cohesion', 'condensin', 'aurora', 'polo', 'checkpoint']
    
    # Convert keywords to lowercase for case-insensitive matching
    target_keywords = [kw.lower() for kw in target_keywords]
    Analyze novelty of new clusters compared to ground truth clustering.
    
    Parameters:
    -----------
    clustering_df : pd.DataFrame
        New clustering results with columns: gene_symbol_0, cluster, etc.
    aconcagua_df : pd.DataFrame  
        Ground truth clustering with columns: gene_symbol_0, cluster, etc.
    enrichment_df : pd.DataFrame
        KEGG/CORUM enrichment results with columns: cluster, KEGG_enriched_groups, CORUM_enriched_groups, etc.
    mozzarellm_df : pd.DataFrame
        LLM analysis results with columns: cluster_id, cluster_biological_process, etc.
    gene_col : str
        Column name for genes (default: 'gene_symbol_0')
    new_cluster_col : str
        Column name for new cluster assignments (default: 'cluster')  
    old_cluster_col : str
        Column name for old cluster assignments (default: 'cluster')
    jaccard_threshold : float
        Threshold for considering a cluster "novel" (default: 0.3)
    target_keywords : list
        Keywords to search for in biological_process and follow_up_suggestion 
        (default: ['kinetochore', 'centromere', 'chromosome', 'mitosis', 'spindle', 'CENP'])
        
    Returns:
    --------
    pd.DataFrame
        Analysis results sorted by novelty metrics
    """
    
    # Merge new clustering with ground truth
    merged_data = clustering_df.merge(
        aconcagua_df, 
        on=gene_col, 
        how='inner',
        suffixes=('_new', '_old')
    )
    
    if merged_data.empty:
        print("Warning: No overlapping genes found between datasets")
        return pd.DataFrame()
    
    print(f"Found {len(merged_data)} overlapping genes")
    
    # Get unique clusters
    new_clusters = merged_data[f'{new_cluster_col}_new'].unique()
    old_clusters = merged_data[f'{old_cluster_col}_old'].unique()
    
    results = []
    
    for new_cluster in new_clusters:
        # Get genes in this new cluster
        new_cluster_genes = set(merged_data[merged_data[f'{new_cluster_col}_new'] == new_cluster][gene_col])
        
        # Calculate Jaccard index with all old clusters
        jaccard_scores = {}
        for old_cluster in old_clusters:
            old_cluster_genes = set(merged_data[merged_data[f'{old_cluster_col}_old'] == old_cluster][gene_col])
            
            intersection = len(new_cluster_genes.intersection(old_cluster_genes))
            union = len(new_cluster_genes.union(old_cluster_genes))
            
            if union > 0:
                jaccard_scores[old_cluster] = intersection / union
            else:
                jaccard_scores[old_cluster] = 0
        
        # Find best matching old cluster
        max_jaccard = max(jaccard_scores.values()) if jaccard_scores else 0
        best_old_cluster = max(jaccard_scores, key=jaccard_scores.get) if jaccard_scores else None
        
        # Get genes from the closest correlated cluster
        closest_cluster_genes = set()
        if best_old_cluster is not None:
            closest_cluster_genes = set(merged_data[merged_data[f'{old_cluster_col}_old'] == best_old_cluster][gene_col])
        
        # Calculate average normalized_potential_to_nontargeting for this cluster
        cluster_potential_scores = clustering_df[clustering_df[new_cluster_col] == new_cluster]['normalized_potential_to_nontargeting']
        avg_potential_score = cluster_potential_scores.mean() if len(cluster_potential_scores) > 0 else 0
        
        # Calculate entropy of old cluster composition
        old_cluster_composition = merged_data[merged_data[f'{new_cluster_col}_new'] == new_cluster][f'{old_cluster_col}_old'].value_counts()
        if len(old_cluster_composition) > 1:
            proportions = old_cluster_composition / old_cluster_composition.sum()
            entropy = -sum(p * np.log2(p) for p in proportions if p > 0)
        else:
            entropy = 0
        
        # Get enrichment data for this cluster
        enrichment_data = enrichment_df[enrichment_df['cluster'] == new_cluster]
        
        # Extract enrichment information
        kegg_terms = ""
        corum_terms = ""
        string_precision = 0
        cluster_size_enrichment = 0
        
        if not enrichment_data.empty:
            row = enrichment_data.iloc[0]  # Take first row if multiple
            kegg_terms = str(row.get('KEGG_enriched_groups', '')).replace('nan', '').replace('NaN', '')
            corum_terms = str(row.get('CORUM_enriched_groups', '')).replace('nan', '').replace('NaN', '')
            string_precision = row.get('STRING_precision', 0) if pd.notna(row.get('STRING_precision', 0)) else 0
            cluster_size_enrichment = row.get('cluster_size', 0) if pd.notna(row.get('cluster_size', 0)) else 0
        
        # Get LLM analysis for this cluster
        biological_process = ""
        pathway_confidence = ""
        importance_score = 0
        follow_up = ""
        established_genes = ""
        uncharacterized_genes = ""
        novel_role_genes = ""
        percent_established = 0
        
        llm_data = mozzarellm_df[mozzarellm_df['cluster_id'] == new_cluster]
        if not llm_data.empty:
            row = llm_data.iloc[0]  # Take first row if multiple
            biological_process = str(row.get('cluster_biological_process', '')).replace('nan', '').replace('NaN', '')
            pathway_confidence = str(row.get('pathway_confidence_level', '')).replace('nan', '').replace('NaN', '')
            importance_score = row.get('cluster_importance_score', 0) if pd.notna(row.get('cluster_importance_score', 0)) else 0
            follow_up = str(row.get('follow_up_suggestion', '')).replace('nan', '').replace('NaN', '')
            established_genes = str(row.get('established_genes', '')).replace('nan', '').replace('NaN', '')
            uncharacterized_genes = str(row.get('uncharacterized_genes', '')).replace('nan', '').replace('NaN', '')
            novel_role_genes = str(row.get('novel_role_genes', '')).replace('nan', '').replace('NaN', '')
            
            # Calculate percent established genes
            established_count = row.get('established_gene_count', 0) if pd.notna(row.get('established_gene_count', 0)) else 0
            total_count = row.get('total_gene_count', 0) if pd.notna(row.get('total_gene_count', 0)) else 0
            percent_established = (established_count / total_count * 100) if total_count > 0 else 0
        
        # Search for target keywords
        keywords_found = []
        search_text = f"{biological_process} {follow_up}".lower()
        
        for keyword in target_keywords:
            if keyword in search_text:
                keywords_found.append(keyword)
        
        keywords_found_str = "; ".join(keywords_found) if keywords_found else ""
        
        # Compile results
        result = {
            'new_cluster': new_cluster,
            'cluster_size': len(new_cluster_genes),
            'avg_potential_score': avg_potential_score,
            'max_jaccard': max_jaccard,
            'best_old_cluster': best_old_cluster,
            'entropy': entropy,
            'is_novel': max_jaccard < jaccard_threshold,
            'string_precision': string_precision,
            'kegg_terms': kegg_terms if kegg_terms != 'nan' else "",
            'corum_terms': corum_terms if corum_terms != 'nan' else "",
            'biological_process': biological_process if biological_process != 'nan' else "",
            'pathway_confidence': pathway_confidence if pathway_confidence != 'nan' else "",
            'importance_score': importance_score,
            'percent_established': percent_established,
            'follow_up_suggestion': follow_up if follow_up != 'nan' else "",
            'keywords_found': keywords_found_str,
            'established_genes': established_genes if established_genes != 'nan' else "",
            'uncharacterized_genes': uncharacterized_genes if uncharacterized_genes != 'nan' else "",
            'novel_role_genes': novel_role_genes if novel_role_genes != 'nan' else "",
            'genes': ','.join(sorted(new_cluster_genes)),
            'closest_cluster_genes': ','.join(sorted(closest_cluster_genes))
        }
        
        results.append(result)
    
    # Convert to DataFrame and sort by novelty
    results_df = pd.DataFrame(results)
    
    # Sort by: novelty first, then by entropy (higher = more mixed origins), then by importance
    results_df = results_df.sort_values([
        'is_novel', 'max_jaccard', 'entropy', 'importance_score'
    ], ascending=[False, True, False, False])
    
    # Add rank for easy reference
    results_df.reset_index(drop=True, inplace=True)
    results_df['novelty_rank'] = range(1, len(results_df) + 1)
    
    print(f"\nAnalysis complete!")
    print(f"Total clusters analyzed: {len(results_df)}")
    print(f"Novel clusters (Jaccard < {jaccard_threshold}): {sum(results_df['is_novel'])}")
    print(f"Clusters with target keywords: {sum(results_df['keywords_found'] != '')}")
    print(f"Average max Jaccard: {results_df['max_jaccard'].mean():.3f}")
    
    return results_df

# Helper function to save results
def save_cluster_results(results_df, output_prefix='cluster_novelty_analysis'):
    """
    Save cluster analysis results to CSV files.
    
    Parameters:
    -----------
    results_df : pd.DataFrame
        Results from analyze_cluster_novelty function
    output_prefix : str
        Prefix for output filenames (default: 'cluster_novelty_analysis')
    
    Returns:
    --------
    dict
        Dictionary with paths to saved files
    """
    saved_files = {}
    
    # Save all clusters
    all_file = f'{output_prefix}_all.csv'
    results_df.to_csv(all_file, index=False)
    saved_files['all_clusters'] = all_file
    print(f"Saved all clusters to: {all_file}")
    
    # Save keyword clusters only
    keyword_clusters = results_df[results_df['keywords_found'] != ""].copy()
    if not keyword_clusters.empty:
        keyword_file = f'{output_prefix}_keywords_only.csv'
        keyword_clusters.to_csv(keyword_file, index=False)
        saved_files['keyword_clusters'] = keyword_file
        print(f"Saved {len(keyword_clusters)} keyword clusters to: {keyword_file}")
    else:
        print("No clusters with target keywords found - keyword file not created")
        saved_files['keyword_clusters'] = None
    
    return saved_files

In [22]:
clustering = "brieflow_output/cluster/DAPI_ACA_CENPT/Interphase/15/phate_leiden_clustering.tsv"
enrichment = "brieflow_output/cluster/DAPI_ACA_CENPT/Interphase/15/CB-Real__combined_table.tsv"
mozzarellm = "brieflow_output/cluster/DAPI_ACA_CENPT/Interphase/15/mozzarellm_analysis/claude-3-7-sonnet-20250219_clusters.csv"
aconcagua_clustering = "/lab/ops_analysis/cheeseman/aconcagua_clustering.csv"
clustering = pd.read_csv(clustering, sep="\t")
display(clustering)
enrichment = pd.read_csv(enrichment, sep="\t")
display(enrichment)
mozzarellm = pd.read_csv(mozzarellm)
display(mozzarellm)
aconcagua_clustering = pd.read_csv(aconcagua_clustering)
display(aconcagua_clustering)

,gene_symbol_0,cell_count,PHATE_0,PHATE_1,cluster,uniprot_entry,uniprot_function,uniprot_link,mean_potential_to_nontargeting,normalized_potential_to_nontargeting
0,RPL18,67,-0.058742,-0.059293,0,Q07020,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/Q07020/entry,4.568376,0.674970
1,UBA52,93,-0.050926,-0.053709,0,P62987,[Ubiquitin]: Exists either covalently attached...,https://www.uniprot.org/uniprotkb/P62987/entry,4.045695,0.593402
2,RPL19,93,-0.059679,-0.059047,0,P84098,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/P84098/entry,4.584350,0.677463
3,RPL8,92,-0.061155,-0.059367,0,P62917,Component of the large ribosomal subunit. The ...,https://www.uniprot.org/uniprotkb/P62917/entry,4.671551,0.691071
4,RPL17-C18orf32,69,-0.051037,-0.050890,0,NaN,NaN,NaN,3.950824,0.578596
...,...,...,...,...,...,...,...,...,...,...
5291,RBM14,298,0.001224,0.006361,505,Q96PK6,Isoform 1 may function as a nuclear receptor c...,https://www.uniprot.org/uniprotkb/Q96PK6/entry,0.315507,0.011278
5292,MSTO1,159,-0.000752,0.005532,505,Q9BUK6,Involved in the regulation of mitochondrial di...,https://www.uniprot.org/uniprotkb/Q9BUK6/entry,0.260204,0.002648
5293,nontargeting_AGAAGGGCCGT,161,-0.000150,0.004390,505,NaN,NaN,NaN,0.259018,0.002463
5294,ZZZ3,392,0.004784,0.005009,505,Q8IYH5,Histone H3 reader that is required for the ATA...,https://www.uniprot.org/uniprotkb/Q8IYH5/entry,0.419697,0.027538
5295,EVPL,233,-0.000042,0.005005,505,Q92817,Component of the cornified envelope of keratin...,https://www.uniprot.org/uniprotkb/Q92817/entry,0.271627,0.004430

,cluster,genes,cluster_size,enriched_in,STRING_precision,STRING_true_positives,CORUM_enriched_groups,CORUM_enriched_ids,KEGG_enriched_groups,KEGG_enriched_ids
0,0,AAMP; BANP; BDP1; BRF1; BRIX1; DDX27; DDX51; D...,68,"CORUM, KEGG, STRING",0.410887,936.0,5.0,"60S ribosomal subunit, cytoplasmic, Nop56p-ass...",1.0,KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION
1,1,AGAP4; ATAD5; CAPRIN1; CCNA2; CDC45; CDC6; CDC...,48,"CORUM, KEGG",0.056738,64.0,11.0,"DNA polymerase alpha-primase complex, DNA synt...",8.0,"KEGG_MEDICUS_REFERENCE_CORE_NER_REACTION, KEGG..."
2,2,ABCE1; CASZ1; CBWD1; CTNNBL1; DDX23; EFTUD2; L...,44,"CORUM, STRING",0.323467,306.0,25.0,"(E.F.G) complex, 12S U11 snRNP, 17S U2 snRNP, ...",NaN,NaN
3,3,C12orf45; CCDC107; COPS4; DCAF13; DNTTIP2; DUS...,41,"CORUM, STRING",0.326829,268.0,1.0,NOL11-UTP4-WDR43 complex,NaN,NaN
4,4,BMS1; BUD23; CSNK1A1; DDX10; DDX18; DDX21; DHX...,40,"CORUM, KEGG, STRING",0.523077,408.0,3.0,"40S ribosomal subunit, cytoplasmic, Nop56p-ass...",1.0,KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION
...,...,...,...,...,...,...,...,...,...,...
501,501,CNEP1R1; FBXW12; RBBP7; STMN1; USP17L21,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
502,502,CLASRP; KCNK4; MRPL11; NAALADL1; ZNF468,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
503,503,EXT1; MAML1; PTRH1; SAMM50; TMEM69,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
504,504,ABI3; COG1; KLHL11; OGA; OR4D2,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
505,505,EVPL; MSTO1; RBM14; ZZZ3; nontargeting_AGAAGGG...,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN

,cluster_id,cluster_biological_process,pathway_confidence_level,cluster_importance_score,follow_up_suggestion,established_genes,established_gene_count,uncharacterized_genes,uncharacterized_gene_count,novel_role_genes,...,total_gene_count,highest_unchar_importance,average_unchar_importance,high_unchar_genes,high_unchar_gene_count,highest_novel_role_importance,average_novel_role_importance,high_novel_role_genes,high_novel_role_gene_count,all_cluster_genes
0,0,Ribosome biogenesis and 60S ribosomal subunit ...,High,2.64,Cluster 0 shows a strong signature of ribosome...,RPL18;UBA52;RPL19;RPL8;RPL27;RPL14;RPL13;RPL30...,55,RPL17-C18orf32;ELOA3B;NIFK,3,NEPRO;AAMP;BANP;PCGF2;SRRT;BDP1;BRF1;POLR3E;ZN...,...,68,8,7.0,ELOA3B:8,1,7,4.90,NaN,0,RPL18;UBA52;RPL19;RPL8;RPL27;RPL14;RPL13;RPL30...
1,1,DNA replication and replication fork progression,High,3.12,This cluster shows a highly coherent signature...,MCM10;DUT;DTL;PCNA;ATAD5;CDC45;POLE;TICRR;RRM2...,35,FAM25A;FAM25C;FAM25G;GOLGA6L6;SPDYE1,5,HSPD1;TERF2;SKP2;RBBP8;HMGB1;GRID2IP;AGAP4;CAP...,...,48,8,7.4,FAM25A:8;FAM25C:8;FAM25G:8,3,8,6.25,GRID2IP:8,1,MCM10;DUT;DTL;PCNA;ATAD5;CDC45;POLE;TICRR;RRM2...
2,2,pre-mRNA splicing and spliceosome assembly,High,2.64,This cluster shows a highly coherent signature...,SMNDC1;SNRNP200;SNRPE;EFTUD2;PRPF6;LSM2;SNRPG;...,30,CBWD1;RBM42,2,ABCE1;RUVBL1;RUVBL2;UBL5;PPP4C;USPL1;VCP;ZNF20...,...,43,7,6.0,NaN,0,8,5.36,ABCE1:8,1,SMNDC1;SNRNP200;SNRPE;EFTUD2;PRPF6;LSM2;SNRPG;...
3,3,Ribosome biogenesis and rRNA processing,High,2.97,Cluster 3 represents a highly coherent group o...,UTP4;WDR36;POLR1B;ZNRD1;RRN3;NOP56;WDR3;RRP9;U...,30,CCDC107;NOL10,2,XRCC5;COPS4;DNTTIP2;ZCCHC9;DUSP11;SBNO1;METAP2...,...,41,9,8.0,CCDC107:9,1,7,4.67,NaN,0,UTP4;WDR36;POLR1B;ZNRD1;RRN3;NOP56;WDR3;RRP9;U...
4,4,Small ribosomal subunit (40S) biogenesis and p...,High,2.10,Cluster 4 represents a highly coherent group o...,RPS3A;RPSA;IMP4;RPS5;RPS7;BMS1;RPS12;PNO1;FBL;...,34,NaN,0,DDX10;DDX18;DDX21;XPO1;EIF3B;CSNK1A1,...,40,0,0.0,NaN,0,7,5.00,NaN,0,RPS3A;RPSA;IMP4;RPS5;RPS7;BMS1;RPS12;PNO1;FBL;...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,501,Microtubule dynamics and cell cycle regulation,Medium,1.40,This cluster reveals a microtubule dynamics an...,STMN1;RBBP7,2,NaN,0,CNEP1R1;USP17L21;FBXW12,...,5,0,0.0,NaN,0,7,6.00,NaN,0,STMN1;RBBP7;CNEP1R1;USP17L21;FBXW12
502,502,No coherent biological pathway,Low,0.88,Cluster 502 contains functionally diverse gene...,NaN,0,ZNF468;CLASRP,2,MRPL11,...,3,8,7.0,ZNF468:8,1,5,5.00,NaN,0,ZNF468;CLASRP;MRPL11
503,503,Mitochondrial protein quality control and memb...,Medium,1.98,This cluster reveals a potential functional ne...,SAMM50,1,TMEM69,1,PTRH1;EXT1;MAML1,...,5,9,9.0,TMEM69:9,1,7,6.00,NaN,0,SAMM50;TMEM69;PTRH1;EXT1;MAML1
504,504,Golgi trafficking and protein glycosylation,Medium,1.40,This cluster reveals a potential functional re...,OGA;COG1,2,OR4D2,1,KLHL11;ABI3,...,5,7,7.0,NaN,0,6,5.50,NaN,0,OGA;COG1;OR4D2;KLHL11;ABI3
505,505,No coherent biological pathway,Low,0.50,This cluster lacks a coherent biological pathw...,NaN,0,NaN,0,RBM14;MSTO1;ZZZ3;EVPL,...,4,0,0.0,NaN,0,5,4.00,NaN,0,RBM14;MSTO1;ZZZ3;EVPL

,gene_symbol_0,cell_count,PHATE_0,PHATE_1,cluster,uniprot_entry,uniprot_function,uniprot_link
0,SDHAF2,5431,0.002343,0.005769,0,Q9NX18,Plays an essential role in the assembly of suc...,https://www.uniprot.org/uniprotkb/Q9NX18/entry
1,FOLR3,8046,0.003512,0.007478,0,P41439,Binds to folate and reduced folic acid derivat...,https://www.uniprot.org/uniprotkb/P41439/entry
2,SCGB1D1,5083,0.003566,0.004751,0,O95968,"May bind androgens and other steroids, may als...",https://www.uniprot.org/uniprotkb/O95968/entry
3,PPP2R5B,5089,0.003158,0.007585,0,Q15173,As the regulatory component of the serine/thre...,https://www.uniprot.org/uniprotkb/Q15173/entry
4,RASGRP2,8026,0.002144,0.007154,0,Q7LDG7,Functions as a calcium- and DAG-regulated nucl...,https://www.uniprot.org/uniprotkb/Q7LDG7/entry
...,...,...,...,...,...,...,...,...
5294,TBRG4,5710,0.007220,0.005894,249,Q969Z0,Plays a role in processing of mitochondrial RN...,https://www.uniprot.org/uniprotkb/Q969Z0/entry
5295,MAGOHB,3399,0.009651,0.005044,250,Q96A72,Required for pre-mRNA splicing as component of...,https://www.uniprot.org/uniprotkb/Q96A72/entry
5296,RIOK1,3986,0.007534,0.003439,250,Q9BRS2,Involved in the final steps of cytoplasmic mat...,https://www.uniprot.org/uniprotkb/Q9BRS2/entry
5297,RBM18,5335,0.001253,0.006475,250,Q96H35,NaN,https://www.uniprot.org/uniprotkb/Q96H35/entry
5298,MBTPS1,4924,0.011762,0.005758,250,Q14703,Serine protease that cleaves after hydrophobic...,https://www.uniprot.org/uniprotkb/Q14703/entry

In [23]:
custom_keywords = ['kinetochore', 'centromere', 'CENP', 'mitosis']
results = analyze_cluster_novelty(clustering, aconcagua_clustering, enrichment, mozzarellm, 
                                  target_keywords=custom_keywords)
saved_files = save_cluster_results(results, 'cenpt_screen_results')

# View most novel clusters
print("Top 10 most novel clusters:")
print(results[results['is_novel']].head(10)[['new_cluster', 'max_jaccard', 'entropy', 'biological_process', 'keywords_found']])

# View clusters with target keywords
print("Clusters with target keywords:")
print(results[results['keywords_found'] != ""][['new_cluster', 'keywords_found', 'biological_process']])

Found 5031 overlapping genes

Analysis complete!
Total clusters analyzed: 506
Novel clusters (Jaccard < 0.3): 498
Clusters with target keywords: 30
Average max Jaccard: 0.072
Saved all clusters to: cenpt_screen_results_all.csv
Saved 30 keyword clusters to: cenpt_screen_results_keywords_only.csv
Top 10 most novel clusters:
   new_cluster  max_jaccard   entropy  \
0          321     0.030303  3.169925
1          469     0.030303  2.807355
2          331     0.031250  3.169925
3          184     0.031250  3.169925
4          380     0.033333  2.584963
5          482     0.034483  2.807355
6          259     0.037037  3.169925
7          477     0.037037  2.128085
8           21     0.038462  4.000000
9          205     0.038462  3.000000

                                  biological_process keywords_found
0    Chromatin organization and histone modification
1  Intracellular transport and protein quality co...
2                     No coherent biological pathway
3       Mitochondrial ribosome assembly and function
4                     No coherent biological pathway    kinetochore
5     Chromatin remodeling and epigenetic regulation
6  Ribosome biogenesis and nuclear-cytoplasmic tr...
7   Cellular stress response and protein homeostasis
8  One-carbon metabolism and folate-dependent pat...
9  Mitotic chromosome segregation and spindle ass...
Clusters with target keywords:
     new_cluster           keywords_found  \
4            380              kinetochore
40           351              kinetochore
66           423                  mitosis
86           131                  mitosis
91           170               centromere
94            90                  mitosis
122          115                  mitosis
124           57     kinetochore; mitosis
174          139     kinetochore; mitosis
185          303               centromere
196          264                  mitosis
201          405                  mitosis
209          368              kinetochore
211          296                  mitosis
220           59                  mitosis
247          442                  mitosis
252          461     kinetochore; mitosis
260          474                  mitosis
271          404              kinetochore
283          153               centromere
341          171                  mitosis
347          299               centromere
406          226     kinetochore; mitosis
409          313     kinetochore; mitosis
417          400              kinetochore
448           89                  mitosis
449          310                  mitosis
483           41                  mitosis
492           15  kinetochore; centromere
494           30                  mitosis

                                    biological_process
4                       No coherent biological pathway
40   Mitotic spindle assembly and chromosome segreg...
66            Mitotic spindle assembly and cytokinesis
86             Mitotic cell cycle regulation via APC/C
91         Mitochondrial protein import and processing
94                       Cell division and cytokinesis
122                      Mitotic cell cycle regulation
124  Mitotic spindle assembly and chromosome segreg...
174                      Mitotic cell cycle regulation
185      RNA processing and transcriptional regulation
196  Cell cycle regulation and mitotic spindle asse...
201  Microtubule dynamics and mitotic spindle regul...
209  Mitotic chromosome regulation and cell cycle c...
211  Mitotic spindle assembly and cell cycle regula...
220          Mitochondrial protein import and assembly
247  Mitotic spindle assembly and chromosome segreg...
252  Mitotic spindle organization and chromosome se...
260  Mitotic checkpoint signaling and chromosome se...
271  Mitotic spindle organization and kinetochore f...
283                  Endosomal sorting and trafficking
341         Mitochondrial DNA replication and maintece
347           Epigenetic regulation of gene expression
406      Cell cycle regulation and mitotic progression
409      Cell cycle regulation and mitotic progression
417  Chromosome segregation and sister chromatid co...
448      Cell cycle regulation and chromosome dynamics
449            Cell cycle regulation and mitotic entry
483  Chromosome condensation and mitotic chromosome...
492    Kinetochore assembly and chromosome segregation
494    NSL histone acetyltransferase complex signaling

In [24]:
clustering = "brieflow_output/cluster/DAPI_VIMENTIN_ITGB1/Interphase/15/phate_leiden_clustering.tsv"
enrichment = "brieflow_output/cluster/DAPI_VIMENTIN_ITGB1/Interphase/15/CB-Real__combined_table.tsv"
mozzarellm = "brieflow_output/cluster/DAPI_VIMENTIN_ITGB1/Interphase/15/mozzarellm_analysis/claude-3-7-sonnet-20250219_clusters.csv"
aconcagua_clustering = "/lab/ops_analysis/cheeseman/aconcagua_clustering.csv"
clustering = pd.read_csv(clustering, sep="\t")
display(clustering)
enrichment = pd.read_csv(enrichment, sep="\t")
display(enrichment)
mozzarellm = pd.read_csv(mozzarellm)
display(mozzarellm)
aconcagua_clustering = pd.read_csv(aconcagua_clustering)
display(aconcagua_clustering)

,gene_symbol_0,cell_count,PHATE_0,PHATE_1,cluster,uniprot_entry,uniprot_function,uniprot_link,mean_potential_to_nontargeting,normalized_potential_to_nontargeting
0,RPL7,155,-0.117834,-0.016559,0,P18124,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/P18124/entry,7.411278,0.984631
1,RPL10,188,-0.113073,-0.015562,0,P27635,Component of the large ribosomal subunit (PubM...,https://www.uniprot.org/uniprotkb/P27635/entry,7.111462,0.943287
2,RPL13A,208,-0.114349,-0.016143,0,P40429,Associated with ribosomes but is not required ...,https://www.uniprot.org/uniprotkb/P40429/entry,7.191240,0.954288
3,PEX13,290,-0.067548,-0.007744,0,Q92968,"Component of the PEX13-PEX14 docking complex, ...",https://www.uniprot.org/uniprotkb/Q92968/entry,4.263796,0.550602
4,BOP1,190,-0.088212,-0.010658,0,Q14137,"Component of the PeBoW complex, which is requi...",https://www.uniprot.org/uniprotkb/Q14137/entry,5.553396,0.728434
...,...,...,...,...,...,...,...,...,...,...
5291,MTCH2,263,0.000792,0.001325,508,Q9Y6C9,Protein insertase that mediates insertion of t...,https://www.uniprot.org/uniprotkb/Q9Y6C9/entry,0.337854,0.009226
5292,XRCC6,299,-0.000930,-0.011476,508,P12956,Single-stranded DNA-dependent ATP-dependent he...,https://www.uniprot.org/uniprotkb/P12956/entry,0.975402,0.097142
5293,COA3,128,0.002222,-0.000950,508,Q9Y2R0,Core component of the MITRAC (mitochondrial tr...,https://www.uniprot.org/uniprotkb/Q9Y2R0/entry,0.424310,0.021148
5294,CDC42,246,0.003742,-0.028796,508,P60953,Plasma membrane-associated small GTPase which ...,https://www.uniprot.org/uniprotkb/P60953/entry,1.981820,0.235924
5295,SON,158,0.003198,-0.029336,508,P18583,RNA-binding protein that acts as a mRNA splici...,https://www.uniprot.org/uniprotkb/P18583/entry,2.029083,0.242441

,cluster,genes,cluster_size,enriched_in,STRING_precision,STRING_true_positives,CORUM_enriched_groups,CORUM_enriched_ids,KEGG_enriched_groups,KEGG_enriched_ids
0,0,AAMP; BDP1; BOP1; CEBPZ; DDX27; DDX56; EIF6; E...,60,"CORUM, KEGG, STRING",0.503955,892.0,5.0,"60S ribosomal subunit, cytoplasmic, Nop56p-ass...",1.0,KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION
1,1,AGAP4; AGAP6; ATAD5; CCNA2; CDC45; CDC6; CDC7;...,49,"CORUM, KEGG",0.053571,63.0,11.0,"DNA polymerase alpha-primase complex, DNA synt...",10.0,"KEGG_MEDICUS_REFERENCE_CORE_NER_REACTION, KEGG..."
2,2,ABCE1; BRF2; CKS1B; DDX23; ECD; EFTUD2; ELL; I...,46,"CORUM, STRING",0.318841,330.0,20.0,"(E.F.G) complex, 12S U11 snRNP, 17S U2 snRNP, ...",NaN,NaN
3,3,BUD23; DDX10; DDX47; DHX37; EIF4E; FAU; FBL; I...,38,"CORUM, KEGG, STRING",0.544808,383.0,3.0,"40S ribosomal subunit, cytoplasmic, Nop56p-ass...",1.0,KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION
4,4,CASTOR2; CDC73; CTDP1; CTR9; GTF2A1; GTF2A2; G...,36,"CORUM, KEGG, STRING",0.431746,272.0,28.0,"ARC complex, ARC-L complex, ARC92-Mediator com...",1.0,KEGG_MEDICUS_REFERENCE_TRANSCRIPTION_COUPLED_NER
...,...,...,...,...,...,...,...,...,...,...
504,504,ATP6V0A2; DHRS4; MIB1; NUF2; SUGP2; VMA21,6,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
505,505,CCND3; POLD2; PPM1G; RANGAP1; TRIR,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
506,506,KLF16; MRPS11; RNF115; TMEM242; nontargeting_C...,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
507,507,AKAP1; CCDC47; ICE2; MPDU1; OGA,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
508,508,CDC42; COA3; MTCH2; SON; XRCC6,5,NaN,0.000000,0.0,NaN,NaN,NaN,NaN

,cluster_id,cluster_biological_process,pathway_confidence_level,cluster_importance_score,follow_up_suggestion,established_genes,established_gene_count,uncharacterized_genes,uncharacterized_gene_count,novel_role_genes,...,total_gene_count,highest_unchar_importance,average_unchar_importance,high_unchar_genes,high_unchar_gene_count,highest_novel_role_importance,average_novel_role_importance,high_novel_role_genes,high_novel_role_gene_count,all_cluster_genes
0,0,Ribosome biogenesis and 60S ribosomal subunit ...,High,2.97,Cluster 0 shows a highly coherent signature of...,RPL7;RPL10;RPL13A;BOP1;RPL38;RPL6;RPL31;RPL27;...,53,ELOA3D,1,PEX13;AAMP;BDP1;CEBPZ;RBM19,...,59,8,8.0,ELOA3D:8,1,9,6.60,PEX13:9,1,RPL7;RPL10;RPL13A;BOP1;RPL38;RPL6;RPL31;RPL27;...
1,1,DNA replication initiation and progression,High,3.24,This cluster shows a highly coherent signature...,RPA1;RPA2;POLA1;POLA2;PRIM1;CDC6;ORC1;ORC6;MCM...,27,FAM25C;FAM25G;PPIAL4C;KRTAP2-2;NBPF12,5,RAD51;RBBP8;TONSL;MMS22L;TRAIP;MTBP;H3-3A;AGAP...,...,48,9,7.2,FAM25C:9;FAM25G:9,2,7,5.25,NaN,0,RPA1;RPA2;POLA1;POLA2;PRIM1;CDC6;ORC1;ORC6;MCM...
2,2,pre-mRNA splicing and spliceosome assembly,High,2.64,This cluster represents a highly coherent grou...,PRPF40A;UBL5;LSM5;LSM2;LSM6;TXNL4A;SMNDC1;MFAP...,33,SSBP4,1,ICE1;ELL;TUT1;USPL1;RUVBL1;RUVBL2;ZNF207;CKS1B...,...,46,8,8.0,SSBP4:8,1,7,4.00,NaN,0,PRPF40A;UBL5;LSM5;LSM2;LSM6;TXNL4A;SMNDC1;MFAP...
3,3,Small ribosomal subunit biogenesis and processing,High,2.64,Cluster 3 represents a highly coherent group o...,RPS15;FBL;RPS3;RPS13;WDR43;RPS23;RPS7;RPS14;RP...,31,NOM1;SRFBP1,2,DDX10;XPO1;RIOK2;DDX47;EIF4E,...,38,7,6.5,NaN,0,8,6.00,DDX10:8,1,RPS15;FBL;RPS3;RPS13;WDR43;RPS23;RPS7;RPS14;RP...
4,4,RNA Polymerase II-mediated transcription,High,2.64,Cluster 4 shows a highly coherent signature of...,POLR2B;POLR2C;POLR2D;POLR2E;POLR2F;POLR2G;POLR...,33,SLC7A6OS,1,CASTOR2;MST1,...,36,6,6.0,NaN,0,8,7.50,CASTOR2:8,1,POLR2B;POLR2C;POLR2D;POLR2E;POLR2F;POLR2G;POLR...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,504,Vacuolar ATPase-mediated acidification and ves...,Medium,1.40,This cluster reveals a coherent signature cent...,ATP6V0A2;VMA21,2,SUGP2,1,MIB1;NUF2;DHRS4,...,6,6,6.0,NaN,0,7,6.00,NaN,0,ATP6V0A2;VMA21;SUGP2;MIB1;NUF2;DHRS4
505,505,DNA replication and cell cycle regulation,Medium,1.40,Cluster 505 shows a medium-confidence signatur...,CCND3;POLD2,2,TRIR,1,RANGAP1;PPM1G,...,5,6,6.0,NaN,0,7,6.50,NaN,0,CCND3;POLD2;TRIR;RANGAP1;PPM1G
506,506,Mitochondrial translation and ATP synthesis,Medium,1.20,This cluster contains genes involved in mitoch...,MRPS11;TMEM242,2,NaN,0,RNF115;KLF16,...,4,0,0.0,NaN,0,6,5.50,NaN,0,MRPS11;TMEM242;RNF115;KLF16
507,507,Protein glycosylation and ER quality control,Medium,1.40,This cluster reveals a protein glycosylation a...,OGA;MPDU1,2,NaN,0,CCDC47;AKAP1;ICE2,...,5,0,0.0,NaN,0,7,6.00,NaN,0,OGA;MPDU1;CCDC47;AKAP1;ICE2
508,508,RNA splicing and processing,Medium,1.20,This cluster reveals a connection to RNA splic...,SON;XRCC6,2,NaN,0,MTCH2;COA3;CDC42,...,5,0,0.0,NaN,0,6,5.00,NaN,0,SON;XRCC6;MTCH2;COA3;CDC42

,gene_symbol_0,cell_count,PHATE_0,PHATE_1,cluster,uniprot_entry,uniprot_function,uniprot_link
0,SDHAF2,5431,0.002343,0.005769,0,Q9NX18,Plays an essential role in the assembly of suc...,https://www.uniprot.org/uniprotkb/Q9NX18/entry
1,FOLR3,8046,0.003512,0.007478,0,P41439,Binds to folate and reduced folic acid derivat...,https://www.uniprot.org/uniprotkb/P41439/entry
2,SCGB1D1,5083,0.003566,0.004751,0,O95968,"May bind androgens and other steroids, may als...",https://www.uniprot.org/uniprotkb/O95968/entry
3,PPP2R5B,5089,0.003158,0.007585,0,Q15173,As the regulatory component of the serine/thre...,https://www.uniprot.org/uniprotkb/Q15173/entry
4,RASGRP2,8026,0.002144,0.007154,0,Q7LDG7,Functions as a calcium- and DAG-regulated nucl...,https://www.uniprot.org/uniprotkb/Q7LDG7/entry
...,...,...,...,...,...,...,...,...
5294,TBRG4,5710,0.007220,0.005894,249,Q969Z0,Plays a role in processing of mitochondrial RN...,https://www.uniprot.org/uniprotkb/Q969Z0/entry
5295,MAGOHB,3399,0.009651,0.005044,250,Q96A72,Required for pre-mRNA splicing as component of...,https://www.uniprot.org/uniprotkb/Q96A72/entry
5296,RIOK1,3986,0.007534,0.003439,250,Q9BRS2,Involved in the final steps of cytoplasmic mat...,https://www.uniprot.org/uniprotkb/Q9BRS2/entry
5297,RBM18,5335,0.001253,0.006475,250,Q96H35,NaN,https://www.uniprot.org/uniprotkb/Q96H35/entry
5298,MBTPS1,4924,0.011762,0.005758,250,Q14703,Serine protease that cleaves after hydrophobic...,https://www.uniprot.org/uniprotkb/Q14703/entry

In [25]:
custom_keywords = ['integrin', 'itgb1', 'beta1', 'adhesion', 'focal adhesion', 'extracellular matrix', 'ECM', 'laminin', 'collagen', 'fibronectin', 'talin', 'vinculin', 'paxillin', 'FAK', 'kindlin']
results = analyze_cluster_novelty(clustering, aconcagua_clustering, enrichment, mozzarellm, 
                                  target_keywords=custom_keywords)
saved_files = save_cluster_results(results, 'itgb1_screen_results')

# View most novel clusters
print("Top 10 most novel clusters:")
print(results[results['is_novel']].head(10)[['new_cluster', 'max_jaccard', 'entropy', 'biological_process', 'keywords_found']])

# View clusters with target keywords
print("Clusters with target keywords:")
print(results[results['keywords_found'] != ""][['new_cluster', 'keywords_found', 'biological_process']])

Found 5031 overlapping genes

Analysis complete!
Total clusters analyzed: 509
Novel clusters (Jaccard < 0.3): 501
Clusters with target keywords: 24
Average max Jaccard: 0.072
Saved all clusters to: itgb1_screen_results_all.csv
Saved 24 keyword clusters to: itgb1_screen_results_keywords_only.csv
Top 10 most novel clusters:
   new_cluster  max_jaccard   entropy  \
0          498     0.030303  2.321928
1          326     0.031250  2.807355
2          325     0.034483  3.169925
3          348     0.034483  3.169925
4          456     0.034483  2.584963
5          308     0.035714  3.169925
6          419     0.035714  2.807355
7          258     0.037037  3.169925
8          382     0.037037  3.000000
9          289     0.037037  2.807355

                                  biological_process keywords_found
0                         DNA replication and repair
1           Mitochondrial function and bioenergetics
2  Cell cycle regulation and mitotic spindle asse...
3   Programmed cell death (apoptosis and pyroptosis)
4                             mTOR signaling pathway
5           Protein quality control and proteostasis
6  Protein quality control and ubiquitin-proteaso...
7  Cell cycle regulation and mitotic spindle asse...
8  Intracellular trafficking and vesicular transport
9                      Mitotic cell cycle regulation
Clusters with target keywords:
     new_cluster                             keywords_found  \
16           459                       extracellular matrix
19           503                                   adhesion
83            92                                   adhesion
132          272                       extracellular matrix
143          214                                   collagen
144          221                       extracellular matrix
168           63                                   adhesion
175          166                                   adhesion
217          358                       extracellular matrix
248          355                       extracellular matrix
249          369                                   adhesion
261          467                                   adhesion
262          384                                   adhesion
272          364                                   integrin
287          118                                   integrin
327          188                                   adhesion
329           74                                   adhesion
354          492                                   adhesion
377          293                       extracellular matrix
387          336                   adhesion; focal adhesion
410          255             extracellular matrix; collagen
440          438                                   adhesion
460          324                                   adhesion
497            9  integrin; itgb1; adhesion; focal adhesion

                                    biological_process
16       Mitotic checkpoint and kinetochore regulation
19     Protein quality control and degradation pathway
83          mRNA 3' end processing and polyadenylation
132                 RNA quality control and processing
143  Endoplasmic reticulum protein quality control ...
144                        RNA processing and splicing
168        Endocytic trafficking and vesicle transport
175        Cell division and cytoskeletal organization
217          DNA replication and cell cycle regulation
248                     tRNA processing and maturation
249             RNA processing and ribosome biogenesis
261                         DNA replication and repair
262                     No coherent biological pathway
272  ESCRT-mediated vesicular trafficking and prote...
287  Membrane protein trafficking and endoplasmic r...
327  Ribosome quality control and translational reg...
329              Mitochondrial function and biogenesis
354      Transcriptional regulation and RNA processing
377       Mitochondrial RNA processing and translation
387  Cell adhesion and migration via focal adhesion...
410  Extracellular matrix organization and glycosam...
440                     No coherent biological pathway
460                     No coherent biological pathway
497  Integrin-mediated cell adhesion and focal adhe...